
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.0.1
 * Query Engine version: f09f2815f091dbba658cdcd2264306d88bb5bda6
 */
export const prismaVersion: PrismaVersion = {
  client: "7.0.1",
  engine: "f09f2815f091dbba658cdcd2264306d88bb5bda6"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  User: 'User',
  Attachment: 'Attachment',
  Application: 'Application',
  WebAuthnCredential: 'WebAuthnCredential',
  AppConfig: 'AppConfig',
  MonitoredHost: 'MonitoredHost',
  EndPoint: 'EndPoint',
  ProbeResult: 'ProbeResult',
  ProbeHourlyStat: 'ProbeHourlyStat',
  ProbeDailyStat: 'ProbeDailyStat',
  NotificationChannel: 'NotificationChannel',
  NotificationLog: 'NotificationLog',
  ProbeEnv: 'ProbeEnv'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "user" | "attachment" | "application" | "webAuthnCredential" | "appConfig" | "monitoredHost" | "endPoint" | "probeResult" | "probeHourlyStat" | "probeDailyStat" | "notificationChannel" | "notificationLog" | "probeEnv"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    Attachment: {
      payload: Prisma.$AttachmentPayload<ExtArgs>
      fields: Prisma.AttachmentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AttachmentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttachmentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AttachmentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttachmentPayload>
        }
        findFirst: {
          args: Prisma.AttachmentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttachmentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AttachmentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttachmentPayload>
        }
        findMany: {
          args: Prisma.AttachmentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttachmentPayload>[]
        }
        create: {
          args: Prisma.AttachmentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttachmentPayload>
        }
        createMany: {
          args: Prisma.AttachmentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AttachmentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttachmentPayload>[]
        }
        delete: {
          args: Prisma.AttachmentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttachmentPayload>
        }
        update: {
          args: Prisma.AttachmentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttachmentPayload>
        }
        deleteMany: {
          args: Prisma.AttachmentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AttachmentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AttachmentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttachmentPayload>[]
        }
        upsert: {
          args: Prisma.AttachmentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AttachmentPayload>
        }
        aggregate: {
          args: Prisma.AttachmentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAttachment>
        }
        groupBy: {
          args: Prisma.AttachmentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AttachmentGroupByOutputType>[]
        }
        count: {
          args: Prisma.AttachmentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AttachmentCountAggregateOutputType> | number
        }
      }
    }
    Application: {
      payload: Prisma.$ApplicationPayload<ExtArgs>
      fields: Prisma.ApplicationFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ApplicationFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ApplicationFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationPayload>
        }
        findFirst: {
          args: Prisma.ApplicationFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ApplicationFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationPayload>
        }
        findMany: {
          args: Prisma.ApplicationFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationPayload>[]
        }
        create: {
          args: Prisma.ApplicationCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationPayload>
        }
        createMany: {
          args: Prisma.ApplicationCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ApplicationCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationPayload>[]
        }
        delete: {
          args: Prisma.ApplicationDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationPayload>
        }
        update: {
          args: Prisma.ApplicationUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationPayload>
        }
        deleteMany: {
          args: Prisma.ApplicationDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ApplicationUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ApplicationUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationPayload>[]
        }
        upsert: {
          args: Prisma.ApplicationUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ApplicationPayload>
        }
        aggregate: {
          args: Prisma.ApplicationAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateApplication>
        }
        groupBy: {
          args: Prisma.ApplicationGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ApplicationGroupByOutputType>[]
        }
        count: {
          args: Prisma.ApplicationCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ApplicationCountAggregateOutputType> | number
        }
      }
    }
    WebAuthnCredential: {
      payload: Prisma.$WebAuthnCredentialPayload<ExtArgs>
      fields: Prisma.WebAuthnCredentialFieldRefs
      operations: {
        findUnique: {
          args: Prisma.WebAuthnCredentialFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WebAuthnCredentialPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.WebAuthnCredentialFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WebAuthnCredentialPayload>
        }
        findFirst: {
          args: Prisma.WebAuthnCredentialFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WebAuthnCredentialPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.WebAuthnCredentialFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WebAuthnCredentialPayload>
        }
        findMany: {
          args: Prisma.WebAuthnCredentialFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WebAuthnCredentialPayload>[]
        }
        create: {
          args: Prisma.WebAuthnCredentialCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WebAuthnCredentialPayload>
        }
        createMany: {
          args: Prisma.WebAuthnCredentialCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.WebAuthnCredentialCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WebAuthnCredentialPayload>[]
        }
        delete: {
          args: Prisma.WebAuthnCredentialDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WebAuthnCredentialPayload>
        }
        update: {
          args: Prisma.WebAuthnCredentialUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WebAuthnCredentialPayload>
        }
        deleteMany: {
          args: Prisma.WebAuthnCredentialDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.WebAuthnCredentialUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.WebAuthnCredentialUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WebAuthnCredentialPayload>[]
        }
        upsert: {
          args: Prisma.WebAuthnCredentialUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WebAuthnCredentialPayload>
        }
        aggregate: {
          args: Prisma.WebAuthnCredentialAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWebAuthnCredential>
        }
        groupBy: {
          args: Prisma.WebAuthnCredentialGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WebAuthnCredentialGroupByOutputType>[]
        }
        count: {
          args: Prisma.WebAuthnCredentialCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WebAuthnCredentialCountAggregateOutputType> | number
        }
      }
    }
    AppConfig: {
      payload: Prisma.$AppConfigPayload<ExtArgs>
      fields: Prisma.AppConfigFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AppConfigFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppConfigPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AppConfigFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppConfigPayload>
        }
        findFirst: {
          args: Prisma.AppConfigFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppConfigPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AppConfigFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppConfigPayload>
        }
        findMany: {
          args: Prisma.AppConfigFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppConfigPayload>[]
        }
        create: {
          args: Prisma.AppConfigCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppConfigPayload>
        }
        createMany: {
          args: Prisma.AppConfigCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AppConfigCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppConfigPayload>[]
        }
        delete: {
          args: Prisma.AppConfigDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppConfigPayload>
        }
        update: {
          args: Prisma.AppConfigUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppConfigPayload>
        }
        deleteMany: {
          args: Prisma.AppConfigDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AppConfigUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AppConfigUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppConfigPayload>[]
        }
        upsert: {
          args: Prisma.AppConfigUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AppConfigPayload>
        }
        aggregate: {
          args: Prisma.AppConfigAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAppConfig>
        }
        groupBy: {
          args: Prisma.AppConfigGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AppConfigGroupByOutputType>[]
        }
        count: {
          args: Prisma.AppConfigCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AppConfigCountAggregateOutputType> | number
        }
      }
    }
    MonitoredHost: {
      payload: Prisma.$MonitoredHostPayload<ExtArgs>
      fields: Prisma.MonitoredHostFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MonitoredHostFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MonitoredHostPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MonitoredHostFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MonitoredHostPayload>
        }
        findFirst: {
          args: Prisma.MonitoredHostFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MonitoredHostPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MonitoredHostFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MonitoredHostPayload>
        }
        findMany: {
          args: Prisma.MonitoredHostFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MonitoredHostPayload>[]
        }
        create: {
          args: Prisma.MonitoredHostCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MonitoredHostPayload>
        }
        createMany: {
          args: Prisma.MonitoredHostCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MonitoredHostCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MonitoredHostPayload>[]
        }
        delete: {
          args: Prisma.MonitoredHostDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MonitoredHostPayload>
        }
        update: {
          args: Prisma.MonitoredHostUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MonitoredHostPayload>
        }
        deleteMany: {
          args: Prisma.MonitoredHostDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MonitoredHostUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MonitoredHostUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MonitoredHostPayload>[]
        }
        upsert: {
          args: Prisma.MonitoredHostUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MonitoredHostPayload>
        }
        aggregate: {
          args: Prisma.MonitoredHostAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMonitoredHost>
        }
        groupBy: {
          args: Prisma.MonitoredHostGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MonitoredHostGroupByOutputType>[]
        }
        count: {
          args: Prisma.MonitoredHostCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MonitoredHostCountAggregateOutputType> | number
        }
      }
    }
    EndPoint: {
      payload: Prisma.$EndPointPayload<ExtArgs>
      fields: Prisma.EndPointFieldRefs
      operations: {
        findUnique: {
          args: Prisma.EndPointFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EndPointPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.EndPointFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EndPointPayload>
        }
        findFirst: {
          args: Prisma.EndPointFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EndPointPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.EndPointFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EndPointPayload>
        }
        findMany: {
          args: Prisma.EndPointFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EndPointPayload>[]
        }
        create: {
          args: Prisma.EndPointCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EndPointPayload>
        }
        createMany: {
          args: Prisma.EndPointCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.EndPointCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EndPointPayload>[]
        }
        delete: {
          args: Prisma.EndPointDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EndPointPayload>
        }
        update: {
          args: Prisma.EndPointUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EndPointPayload>
        }
        deleteMany: {
          args: Prisma.EndPointDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.EndPointUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.EndPointUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EndPointPayload>[]
        }
        upsert: {
          args: Prisma.EndPointUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EndPointPayload>
        }
        aggregate: {
          args: Prisma.EndPointAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEndPoint>
        }
        groupBy: {
          args: Prisma.EndPointGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EndPointGroupByOutputType>[]
        }
        count: {
          args: Prisma.EndPointCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EndPointCountAggregateOutputType> | number
        }
      }
    }
    ProbeResult: {
      payload: Prisma.$ProbeResultPayload<ExtArgs>
      fields: Prisma.ProbeResultFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ProbeResultFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeResultPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ProbeResultFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeResultPayload>
        }
        findFirst: {
          args: Prisma.ProbeResultFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeResultPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ProbeResultFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeResultPayload>
        }
        findMany: {
          args: Prisma.ProbeResultFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeResultPayload>[]
        }
        create: {
          args: Prisma.ProbeResultCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeResultPayload>
        }
        createMany: {
          args: Prisma.ProbeResultCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ProbeResultCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeResultPayload>[]
        }
        delete: {
          args: Prisma.ProbeResultDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeResultPayload>
        }
        update: {
          args: Prisma.ProbeResultUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeResultPayload>
        }
        deleteMany: {
          args: Prisma.ProbeResultDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ProbeResultUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ProbeResultUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeResultPayload>[]
        }
        upsert: {
          args: Prisma.ProbeResultUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeResultPayload>
        }
        aggregate: {
          args: Prisma.ProbeResultAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProbeResult>
        }
        groupBy: {
          args: Prisma.ProbeResultGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProbeResultGroupByOutputType>[]
        }
        count: {
          args: Prisma.ProbeResultCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProbeResultCountAggregateOutputType> | number
        }
      }
    }
    ProbeHourlyStat: {
      payload: Prisma.$ProbeHourlyStatPayload<ExtArgs>
      fields: Prisma.ProbeHourlyStatFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ProbeHourlyStatFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeHourlyStatPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ProbeHourlyStatFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeHourlyStatPayload>
        }
        findFirst: {
          args: Prisma.ProbeHourlyStatFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeHourlyStatPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ProbeHourlyStatFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeHourlyStatPayload>
        }
        findMany: {
          args: Prisma.ProbeHourlyStatFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeHourlyStatPayload>[]
        }
        create: {
          args: Prisma.ProbeHourlyStatCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeHourlyStatPayload>
        }
        createMany: {
          args: Prisma.ProbeHourlyStatCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ProbeHourlyStatCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeHourlyStatPayload>[]
        }
        delete: {
          args: Prisma.ProbeHourlyStatDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeHourlyStatPayload>
        }
        update: {
          args: Prisma.ProbeHourlyStatUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeHourlyStatPayload>
        }
        deleteMany: {
          args: Prisma.ProbeHourlyStatDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ProbeHourlyStatUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ProbeHourlyStatUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeHourlyStatPayload>[]
        }
        upsert: {
          args: Prisma.ProbeHourlyStatUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeHourlyStatPayload>
        }
        aggregate: {
          args: Prisma.ProbeHourlyStatAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProbeHourlyStat>
        }
        groupBy: {
          args: Prisma.ProbeHourlyStatGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProbeHourlyStatGroupByOutputType>[]
        }
        count: {
          args: Prisma.ProbeHourlyStatCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProbeHourlyStatCountAggregateOutputType> | number
        }
      }
    }
    ProbeDailyStat: {
      payload: Prisma.$ProbeDailyStatPayload<ExtArgs>
      fields: Prisma.ProbeDailyStatFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ProbeDailyStatFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeDailyStatPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ProbeDailyStatFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeDailyStatPayload>
        }
        findFirst: {
          args: Prisma.ProbeDailyStatFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeDailyStatPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ProbeDailyStatFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeDailyStatPayload>
        }
        findMany: {
          args: Prisma.ProbeDailyStatFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeDailyStatPayload>[]
        }
        create: {
          args: Prisma.ProbeDailyStatCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeDailyStatPayload>
        }
        createMany: {
          args: Prisma.ProbeDailyStatCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ProbeDailyStatCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeDailyStatPayload>[]
        }
        delete: {
          args: Prisma.ProbeDailyStatDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeDailyStatPayload>
        }
        update: {
          args: Prisma.ProbeDailyStatUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeDailyStatPayload>
        }
        deleteMany: {
          args: Prisma.ProbeDailyStatDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ProbeDailyStatUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ProbeDailyStatUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeDailyStatPayload>[]
        }
        upsert: {
          args: Prisma.ProbeDailyStatUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeDailyStatPayload>
        }
        aggregate: {
          args: Prisma.ProbeDailyStatAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProbeDailyStat>
        }
        groupBy: {
          args: Prisma.ProbeDailyStatGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProbeDailyStatGroupByOutputType>[]
        }
        count: {
          args: Prisma.ProbeDailyStatCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProbeDailyStatCountAggregateOutputType> | number
        }
      }
    }
    NotificationChannel: {
      payload: Prisma.$NotificationChannelPayload<ExtArgs>
      fields: Prisma.NotificationChannelFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NotificationChannelFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NotificationChannelFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>
        }
        findFirst: {
          args: Prisma.NotificationChannelFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NotificationChannelFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>
        }
        findMany: {
          args: Prisma.NotificationChannelFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>[]
        }
        create: {
          args: Prisma.NotificationChannelCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>
        }
        createMany: {
          args: Prisma.NotificationChannelCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NotificationChannelCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>[]
        }
        delete: {
          args: Prisma.NotificationChannelDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>
        }
        update: {
          args: Prisma.NotificationChannelUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>
        }
        deleteMany: {
          args: Prisma.NotificationChannelDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NotificationChannelUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NotificationChannelUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>[]
        }
        upsert: {
          args: Prisma.NotificationChannelUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationChannelPayload>
        }
        aggregate: {
          args: Prisma.NotificationChannelAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNotificationChannel>
        }
        groupBy: {
          args: Prisma.NotificationChannelGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationChannelGroupByOutputType>[]
        }
        count: {
          args: Prisma.NotificationChannelCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationChannelCountAggregateOutputType> | number
        }
      }
    }
    NotificationLog: {
      payload: Prisma.$NotificationLogPayload<ExtArgs>
      fields: Prisma.NotificationLogFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NotificationLogFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationLogPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NotificationLogFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationLogPayload>
        }
        findFirst: {
          args: Prisma.NotificationLogFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationLogPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NotificationLogFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationLogPayload>
        }
        findMany: {
          args: Prisma.NotificationLogFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationLogPayload>[]
        }
        create: {
          args: Prisma.NotificationLogCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationLogPayload>
        }
        createMany: {
          args: Prisma.NotificationLogCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NotificationLogCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationLogPayload>[]
        }
        delete: {
          args: Prisma.NotificationLogDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationLogPayload>
        }
        update: {
          args: Prisma.NotificationLogUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationLogPayload>
        }
        deleteMany: {
          args: Prisma.NotificationLogDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NotificationLogUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NotificationLogUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationLogPayload>[]
        }
        upsert: {
          args: Prisma.NotificationLogUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificationLogPayload>
        }
        aggregate: {
          args: Prisma.NotificationLogAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNotificationLog>
        }
        groupBy: {
          args: Prisma.NotificationLogGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationLogGroupByOutputType>[]
        }
        count: {
          args: Prisma.NotificationLogCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationLogCountAggregateOutputType> | number
        }
      }
    }
    ProbeEnv: {
      payload: Prisma.$ProbeEnvPayload<ExtArgs>
      fields: Prisma.ProbeEnvFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ProbeEnvFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeEnvPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ProbeEnvFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeEnvPayload>
        }
        findFirst: {
          args: Prisma.ProbeEnvFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeEnvPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ProbeEnvFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeEnvPayload>
        }
        findMany: {
          args: Prisma.ProbeEnvFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeEnvPayload>[]
        }
        create: {
          args: Prisma.ProbeEnvCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeEnvPayload>
        }
        createMany: {
          args: Prisma.ProbeEnvCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ProbeEnvCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeEnvPayload>[]
        }
        delete: {
          args: Prisma.ProbeEnvDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeEnvPayload>
        }
        update: {
          args: Prisma.ProbeEnvUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeEnvPayload>
        }
        deleteMany: {
          args: Prisma.ProbeEnvDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ProbeEnvUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ProbeEnvUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeEnvPayload>[]
        }
        upsert: {
          args: Prisma.ProbeEnvUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProbeEnvPayload>
        }
        aggregate: {
          args: Prisma.ProbeEnvAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProbeEnv>
        }
        groupBy: {
          args: Prisma.ProbeEnvGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProbeEnvGroupByOutputType>[]
        }
        count: {
          args: Prisma.ProbeEnvCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProbeEnvCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  username: 'username',
  email: 'email',
  phone: 'phone',
  role: 'role',
  isBanned: 'isBanned',
  isDeleted: 'isDeleted',
  passwordHash: 'passwordHash'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const AttachmentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  filename: 'filename',
  size: 'size',
  hash: 'hash',
  path: 'path',
  type: 'type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AttachmentScalarFieldEnum = (typeof AttachmentScalarFieldEnum)[keyof typeof AttachmentScalarFieldEnum]


export const ApplicationScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  subTitle: 'subTitle',
  tokenKey: 'tokenKey'
} as const

export type ApplicationScalarFieldEnum = (typeof ApplicationScalarFieldEnum)[keyof typeof ApplicationScalarFieldEnum]


export const WebAuthnCredentialScalarFieldEnum = {
  id: 'id',
  name: 'name',
  userId: 'userId',
  credentialID: 'credentialID',
  credentialPublicKey: 'credentialPublicKey',
  counter: 'counter',
  transports: 'transports',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WebAuthnCredentialScalarFieldEnum = (typeof WebAuthnCredentialScalarFieldEnum)[keyof typeof WebAuthnCredentialScalarFieldEnum]


export const AppConfigScalarFieldEnum = {
  key: 'key',
  value: 'value',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AppConfigScalarFieldEnum = (typeof AppConfigScalarFieldEnum)[keyof typeof AppConfigScalarFieldEnum]


export const MonitoredHostScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  desc: 'desc',
  url: 'url',
  headers: 'headers',
  enabled: 'enabled',
  notifyEnabled: 'notifyEnabled',
  notifyFailureCount: 'notifyFailureCount',
  notifyCooldownMin: 'notifyCooldownMin',
  notifyChannelIds: 'notifyChannelIds'
} as const

export type MonitoredHostScalarFieldEnum = (typeof MonitoredHostScalarFieldEnum)[keyof typeof MonitoredHostScalarFieldEnum]


export const EndPointScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  hostId: 'hostId',
  name: 'name',
  desc: 'desc',
  type: 'type',
  url: 'url',
  method: 'method',
  headers: 'headers',
  timeout: 'timeout',
  bodyContentType: 'bodyContentType',
  bodyContent: 'bodyContent',
  codeContent: 'codeContent',
  intervalTime: 'intervalTime',
  enabled: 'enabled'
} as const

export type EndPointScalarFieldEnum = (typeof EndPointScalarFieldEnum)[keyof typeof EndPointScalarFieldEnum]


export const ProbeResultScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  endPointId: 'endPointId',
  status: 'status',
  responseTime: 'responseTime',
  success: 'success',
  message: 'message'
} as const

export type ProbeResultScalarFieldEnum = (typeof ProbeResultScalarFieldEnum)[keyof typeof ProbeResultScalarFieldEnum]


export const ProbeHourlyStatScalarFieldEnum = {
  endPointId: 'endPointId',
  hourTimestamp: 'hourTimestamp',
  totalChecks: 'totalChecks',
  successCount: 'successCount',
  avgResponseTime: 'avgResponseTime',
  minResponseTime: 'minResponseTime',
  maxResponseTime: 'maxResponseTime'
} as const

export type ProbeHourlyStatScalarFieldEnum = (typeof ProbeHourlyStatScalarFieldEnum)[keyof typeof ProbeHourlyStatScalarFieldEnum]


export const ProbeDailyStatScalarFieldEnum = {
  endPointId: 'endPointId',
  date: 'date',
  totalChecks: 'totalChecks',
  successCount: 'successCount',
  uptimePercentage: 'uptimePercentage',
  avgResponseTime: 'avgResponseTime',
  minResponseTime: 'minResponseTime',
  maxResponseTime: 'maxResponseTime'
} as const

export type ProbeDailyStatScalarFieldEnum = (typeof ProbeDailyStatScalarFieldEnum)[keyof typeof ProbeDailyStatScalarFieldEnum]


export const NotificationChannelScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  webhookUrl: 'webhookUrl',
  headers: 'headers',
  bodyTemplate: 'bodyTemplate',
  enabled: 'enabled'
} as const

export type NotificationChannelScalarFieldEnum = (typeof NotificationChannelScalarFieldEnum)[keyof typeof NotificationChannelScalarFieldEnum]


export const NotificationLogScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  hostId: 'hostId',
  endpointId: 'endpointId',
  channelId: 'channelId',
  eventType: 'eventType',
  title: 'title',
  content: 'content',
  success: 'success',
  errorMsg: 'errorMsg'
} as const

export type NotificationLogScalarFieldEnum = (typeof NotificationLogScalarFieldEnum)[keyof typeof NotificationLogScalarFieldEnum]


export const ProbeEnvScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  key: 'key',
  value: 'value',
  isSecret: 'isSecret',
  desc: 'desc'
} as const

export type ProbeEnvScalarFieldEnum = (typeof ProbeEnvScalarFieldEnum)[keyof typeof ProbeEnvScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'UserRole'
 */
export type EnumUserRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'UserRole'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'EndPointType'
 */
export type EnumEndPointTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'EndPointType'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/logging#the-log-option).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
}
export type GlobalOmitConfig = {
  user?: Prisma.UserOmit
  attachment?: Prisma.AttachmentOmit
  application?: Prisma.ApplicationOmit
  webAuthnCredential?: Prisma.WebAuthnCredentialOmit
  appConfig?: Prisma.AppConfigOmit
  monitoredHost?: Prisma.MonitoredHostOmit
  endPoint?: Prisma.EndPointOmit
  probeResult?: Prisma.ProbeResultOmit
  probeHourlyStat?: Prisma.ProbeHourlyStatOmit
  probeDailyStat?: Prisma.ProbeDailyStatOmit
  notificationChannel?: Prisma.NotificationChannelOmit
  notificationLog?: Prisma.NotificationLogOmit
  probeEnv?: Prisma.ProbeEnvOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

