
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EndPoint` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EndPoint
 * 
 */
export type EndPointModel = runtime.Types.Result.DefaultSelection<Prisma.$EndPointPayload>

export type AggregateEndPoint = {
  _count: EndPointCountAggregateOutputType | null
  _avg: EndPointAvgAggregateOutputType | null
  _sum: EndPointSumAggregateOutputType | null
  _min: EndPointMinAggregateOutputType | null
  _max: EndPointMaxAggregateOutputType | null
}

export type EndPointAvgAggregateOutputType = {
  timeout: number | null
  intervalTime: number | null
}

export type EndPointSumAggregateOutputType = {
  timeout: number | null
  intervalTime: number | null
}

export type EndPointMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  hostId: string | null
  name: string | null
  desc: string | null
  type: $Enums.EndPointType | null
  url: string | null
  method: string | null
  timeout: number | null
  bodyContentType: string | null
  bodyContent: string | null
  codeContent: string | null
  intervalTime: number | null
  enabled: boolean | null
}

export type EndPointMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  hostId: string | null
  name: string | null
  desc: string | null
  type: $Enums.EndPointType | null
  url: string | null
  method: string | null
  timeout: number | null
  bodyContentType: string | null
  bodyContent: string | null
  codeContent: string | null
  intervalTime: number | null
  enabled: boolean | null
}

export type EndPointCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  hostId: number
  name: number
  desc: number
  type: number
  url: number
  method: number
  headers: number
  timeout: number
  bodyContentType: number
  bodyContent: number
  codeContent: number
  intervalTime: number
  enabled: number
  _all: number
}


export type EndPointAvgAggregateInputType = {
  timeout?: true
  intervalTime?: true
}

export type EndPointSumAggregateInputType = {
  timeout?: true
  intervalTime?: true
}

export type EndPointMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  hostId?: true
  name?: true
  desc?: true
  type?: true
  url?: true
  method?: true
  timeout?: true
  bodyContentType?: true
  bodyContent?: true
  codeContent?: true
  intervalTime?: true
  enabled?: true
}

export type EndPointMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  hostId?: true
  name?: true
  desc?: true
  type?: true
  url?: true
  method?: true
  timeout?: true
  bodyContentType?: true
  bodyContent?: true
  codeContent?: true
  intervalTime?: true
  enabled?: true
}

export type EndPointCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  hostId?: true
  name?: true
  desc?: true
  type?: true
  url?: true
  method?: true
  headers?: true
  timeout?: true
  bodyContentType?: true
  bodyContent?: true
  codeContent?: true
  intervalTime?: true
  enabled?: true
  _all?: true
}

export type EndPointAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EndPoint to aggregate.
   */
  where?: Prisma.EndPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EndPoints to fetch.
   */
  orderBy?: Prisma.EndPointOrderByWithRelationInput | Prisma.EndPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EndPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EndPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EndPoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EndPoints
  **/
  _count?: true | EndPointCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EndPointAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EndPointSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EndPointMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EndPointMaxAggregateInputType
}

export type GetEndPointAggregateType<T extends EndPointAggregateArgs> = {
      [P in keyof T & keyof AggregateEndPoint]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEndPoint[P]>
    : Prisma.GetScalarType<T[P], AggregateEndPoint[P]>
}




export type EndPointGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EndPointWhereInput
  orderBy?: Prisma.EndPointOrderByWithAggregationInput | Prisma.EndPointOrderByWithAggregationInput[]
  by: Prisma.EndPointScalarFieldEnum[] | Prisma.EndPointScalarFieldEnum
  having?: Prisma.EndPointScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EndPointCountAggregateInputType | true
  _avg?: EndPointAvgAggregateInputType
  _sum?: EndPointSumAggregateInputType
  _min?: EndPointMinAggregateInputType
  _max?: EndPointMaxAggregateInputType
}

export type EndPointGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  hostId: string
  name: string
  desc: string | null
  type: $Enums.EndPointType
  url: string | null
  method: string | null
  headers: runtime.JsonValue | null
  timeout: number | null
  bodyContentType: string | null
  bodyContent: string | null
  codeContent: string | null
  intervalTime: number | null
  enabled: boolean
  _count: EndPointCountAggregateOutputType | null
  _avg: EndPointAvgAggregateOutputType | null
  _sum: EndPointSumAggregateOutputType | null
  _min: EndPointMinAggregateOutputType | null
  _max: EndPointMaxAggregateOutputType | null
}

type GetEndPointGroupByPayload<T extends EndPointGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EndPointGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EndPointGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EndPointGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EndPointGroupByOutputType[P]>
      }
    >
  >



export type EndPointWhereInput = {
  AND?: Prisma.EndPointWhereInput | Prisma.EndPointWhereInput[]
  OR?: Prisma.EndPointWhereInput[]
  NOT?: Prisma.EndPointWhereInput | Prisma.EndPointWhereInput[]
  id?: Prisma.StringFilter<"EndPoint"> | string
  createdAt?: Prisma.DateTimeFilter<"EndPoint"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EndPoint"> | Date | string
  hostId?: Prisma.StringFilter<"EndPoint"> | string
  name?: Prisma.StringFilter<"EndPoint"> | string
  desc?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  type?: Prisma.EnumEndPointTypeFilter<"EndPoint"> | $Enums.EndPointType
  url?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  method?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  headers?: Prisma.JsonNullableFilter<"EndPoint">
  timeout?: Prisma.IntNullableFilter<"EndPoint"> | number | null
  bodyContentType?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  bodyContent?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  codeContent?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  intervalTime?: Prisma.IntNullableFilter<"EndPoint"> | number | null
  enabled?: Prisma.BoolFilter<"EndPoint"> | boolean
  results?: Prisma.ProbeResultListRelationFilter
  hourlyStats?: Prisma.ProbeHourlyStatListRelationFilter
  dailyStats?: Prisma.ProbeDailyStatListRelationFilter
  monitoredHost?: Prisma.XOR<Prisma.MonitoredHostScalarRelationFilter, Prisma.MonitoredHostWhereInput>
}

export type EndPointOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  hostId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  desc?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  url?: Prisma.SortOrderInput | Prisma.SortOrder
  method?: Prisma.SortOrderInput | Prisma.SortOrder
  headers?: Prisma.SortOrderInput | Prisma.SortOrder
  timeout?: Prisma.SortOrderInput | Prisma.SortOrder
  bodyContentType?: Prisma.SortOrderInput | Prisma.SortOrder
  bodyContent?: Prisma.SortOrderInput | Prisma.SortOrder
  codeContent?: Prisma.SortOrderInput | Prisma.SortOrder
  intervalTime?: Prisma.SortOrderInput | Prisma.SortOrder
  enabled?: Prisma.SortOrder
  results?: Prisma.ProbeResultOrderByRelationAggregateInput
  hourlyStats?: Prisma.ProbeHourlyStatOrderByRelationAggregateInput
  dailyStats?: Prisma.ProbeDailyStatOrderByRelationAggregateInput
  monitoredHost?: Prisma.MonitoredHostOrderByWithRelationInput
}

export type EndPointWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EndPointWhereInput | Prisma.EndPointWhereInput[]
  OR?: Prisma.EndPointWhereInput[]
  NOT?: Prisma.EndPointWhereInput | Prisma.EndPointWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"EndPoint"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EndPoint"> | Date | string
  hostId?: Prisma.StringFilter<"EndPoint"> | string
  name?: Prisma.StringFilter<"EndPoint"> | string
  desc?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  type?: Prisma.EnumEndPointTypeFilter<"EndPoint"> | $Enums.EndPointType
  url?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  method?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  headers?: Prisma.JsonNullableFilter<"EndPoint">
  timeout?: Prisma.IntNullableFilter<"EndPoint"> | number | null
  bodyContentType?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  bodyContent?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  codeContent?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  intervalTime?: Prisma.IntNullableFilter<"EndPoint"> | number | null
  enabled?: Prisma.BoolFilter<"EndPoint"> | boolean
  results?: Prisma.ProbeResultListRelationFilter
  hourlyStats?: Prisma.ProbeHourlyStatListRelationFilter
  dailyStats?: Prisma.ProbeDailyStatListRelationFilter
  monitoredHost?: Prisma.XOR<Prisma.MonitoredHostScalarRelationFilter, Prisma.MonitoredHostWhereInput>
}, "id">

export type EndPointOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  hostId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  desc?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  url?: Prisma.SortOrderInput | Prisma.SortOrder
  method?: Prisma.SortOrderInput | Prisma.SortOrder
  headers?: Prisma.SortOrderInput | Prisma.SortOrder
  timeout?: Prisma.SortOrderInput | Prisma.SortOrder
  bodyContentType?: Prisma.SortOrderInput | Prisma.SortOrder
  bodyContent?: Prisma.SortOrderInput | Prisma.SortOrder
  codeContent?: Prisma.SortOrderInput | Prisma.SortOrder
  intervalTime?: Prisma.SortOrderInput | Prisma.SortOrder
  enabled?: Prisma.SortOrder
  _count?: Prisma.EndPointCountOrderByAggregateInput
  _avg?: Prisma.EndPointAvgOrderByAggregateInput
  _max?: Prisma.EndPointMaxOrderByAggregateInput
  _min?: Prisma.EndPointMinOrderByAggregateInput
  _sum?: Prisma.EndPointSumOrderByAggregateInput
}

export type EndPointScalarWhereWithAggregatesInput = {
  AND?: Prisma.EndPointScalarWhereWithAggregatesInput | Prisma.EndPointScalarWhereWithAggregatesInput[]
  OR?: Prisma.EndPointScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EndPointScalarWhereWithAggregatesInput | Prisma.EndPointScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EndPoint"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EndPoint"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"EndPoint"> | Date | string
  hostId?: Prisma.StringWithAggregatesFilter<"EndPoint"> | string
  name?: Prisma.StringWithAggregatesFilter<"EndPoint"> | string
  desc?: Prisma.StringNullableWithAggregatesFilter<"EndPoint"> | string | null
  type?: Prisma.EnumEndPointTypeWithAggregatesFilter<"EndPoint"> | $Enums.EndPointType
  url?: Prisma.StringNullableWithAggregatesFilter<"EndPoint"> | string | null
  method?: Prisma.StringNullableWithAggregatesFilter<"EndPoint"> | string | null
  headers?: Prisma.JsonNullableWithAggregatesFilter<"EndPoint">
  timeout?: Prisma.IntNullableWithAggregatesFilter<"EndPoint"> | number | null
  bodyContentType?: Prisma.StringNullableWithAggregatesFilter<"EndPoint"> | string | null
  bodyContent?: Prisma.StringNullableWithAggregatesFilter<"EndPoint"> | string | null
  codeContent?: Prisma.StringNullableWithAggregatesFilter<"EndPoint"> | string | null
  intervalTime?: Prisma.IntNullableWithAggregatesFilter<"EndPoint"> | number | null
  enabled?: Prisma.BoolWithAggregatesFilter<"EndPoint"> | boolean
}

export type EndPointCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  desc?: string | null
  type?: $Enums.EndPointType
  url?: string | null
  method?: string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: number | null
  bodyContentType?: string | null
  bodyContent?: string | null
  codeContent?: string | null
  intervalTime?: number | null
  enabled?: boolean
  results?: Prisma.ProbeResultCreateNestedManyWithoutEndPointInput
  hourlyStats?: Prisma.ProbeHourlyStatCreateNestedManyWithoutEndPointInput
  dailyStats?: Prisma.ProbeDailyStatCreateNestedManyWithoutEndPointInput
  monitoredHost: Prisma.MonitoredHostCreateNestedOneWithoutEndpointsInput
}

export type EndPointUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  hostId: string
  name: string
  desc?: string | null
  type?: $Enums.EndPointType
  url?: string | null
  method?: string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: number | null
  bodyContentType?: string | null
  bodyContent?: string | null
  codeContent?: string | null
  intervalTime?: number | null
  enabled?: boolean
  results?: Prisma.ProbeResultUncheckedCreateNestedManyWithoutEndPointInput
  hourlyStats?: Prisma.ProbeHourlyStatUncheckedCreateNestedManyWithoutEndPointInput
  dailyStats?: Prisma.ProbeDailyStatUncheckedCreateNestedManyWithoutEndPointInput
}

export type EndPointUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumEndPointTypeFieldUpdateOperationsInput | $Enums.EndPointType
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bodyContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  codeContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervalTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  results?: Prisma.ProbeResultUpdateManyWithoutEndPointNestedInput
  hourlyStats?: Prisma.ProbeHourlyStatUpdateManyWithoutEndPointNestedInput
  dailyStats?: Prisma.ProbeDailyStatUpdateManyWithoutEndPointNestedInput
  monitoredHost?: Prisma.MonitoredHostUpdateOneRequiredWithoutEndpointsNestedInput
}

export type EndPointUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hostId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumEndPointTypeFieldUpdateOperationsInput | $Enums.EndPointType
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bodyContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  codeContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervalTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  results?: Prisma.ProbeResultUncheckedUpdateManyWithoutEndPointNestedInput
  hourlyStats?: Prisma.ProbeHourlyStatUncheckedUpdateManyWithoutEndPointNestedInput
  dailyStats?: Prisma.ProbeDailyStatUncheckedUpdateManyWithoutEndPointNestedInput
}

export type EndPointCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  hostId: string
  name: string
  desc?: string | null
  type?: $Enums.EndPointType
  url?: string | null
  method?: string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: number | null
  bodyContentType?: string | null
  bodyContent?: string | null
  codeContent?: string | null
  intervalTime?: number | null
  enabled?: boolean
}

export type EndPointUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumEndPointTypeFieldUpdateOperationsInput | $Enums.EndPointType
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bodyContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  codeContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervalTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type EndPointUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hostId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumEndPointTypeFieldUpdateOperationsInput | $Enums.EndPointType
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bodyContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  codeContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervalTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type EndPointListRelationFilter = {
  every?: Prisma.EndPointWhereInput
  some?: Prisma.EndPointWhereInput
  none?: Prisma.EndPointWhereInput
}

export type EndPointOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EndPointCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  hostId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  desc?: Prisma.SortOrder
  type?: Prisma.SortOrder
  url?: Prisma.SortOrder
  method?: Prisma.SortOrder
  headers?: Prisma.SortOrder
  timeout?: Prisma.SortOrder
  bodyContentType?: Prisma.SortOrder
  bodyContent?: Prisma.SortOrder
  codeContent?: Prisma.SortOrder
  intervalTime?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
}

export type EndPointAvgOrderByAggregateInput = {
  timeout?: Prisma.SortOrder
  intervalTime?: Prisma.SortOrder
}

export type EndPointMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  hostId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  desc?: Prisma.SortOrder
  type?: Prisma.SortOrder
  url?: Prisma.SortOrder
  method?: Prisma.SortOrder
  timeout?: Prisma.SortOrder
  bodyContentType?: Prisma.SortOrder
  bodyContent?: Prisma.SortOrder
  codeContent?: Prisma.SortOrder
  intervalTime?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
}

export type EndPointMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  hostId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  desc?: Prisma.SortOrder
  type?: Prisma.SortOrder
  url?: Prisma.SortOrder
  method?: Prisma.SortOrder
  timeout?: Prisma.SortOrder
  bodyContentType?: Prisma.SortOrder
  bodyContent?: Prisma.SortOrder
  codeContent?: Prisma.SortOrder
  intervalTime?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
}

export type EndPointSumOrderByAggregateInput = {
  timeout?: Prisma.SortOrder
  intervalTime?: Prisma.SortOrder
}

export type EndPointScalarRelationFilter = {
  is?: Prisma.EndPointWhereInput
  isNot?: Prisma.EndPointWhereInput
}

export type EndPointCreateNestedManyWithoutMonitoredHostInput = {
  create?: Prisma.XOR<Prisma.EndPointCreateWithoutMonitoredHostInput, Prisma.EndPointUncheckedCreateWithoutMonitoredHostInput> | Prisma.EndPointCreateWithoutMonitoredHostInput[] | Prisma.EndPointUncheckedCreateWithoutMonitoredHostInput[]
  connectOrCreate?: Prisma.EndPointCreateOrConnectWithoutMonitoredHostInput | Prisma.EndPointCreateOrConnectWithoutMonitoredHostInput[]
  createMany?: Prisma.EndPointCreateManyMonitoredHostInputEnvelope
  connect?: Prisma.EndPointWhereUniqueInput | Prisma.EndPointWhereUniqueInput[]
}

export type EndPointUncheckedCreateNestedManyWithoutMonitoredHostInput = {
  create?: Prisma.XOR<Prisma.EndPointCreateWithoutMonitoredHostInput, Prisma.EndPointUncheckedCreateWithoutMonitoredHostInput> | Prisma.EndPointCreateWithoutMonitoredHostInput[] | Prisma.EndPointUncheckedCreateWithoutMonitoredHostInput[]
  connectOrCreate?: Prisma.EndPointCreateOrConnectWithoutMonitoredHostInput | Prisma.EndPointCreateOrConnectWithoutMonitoredHostInput[]
  createMany?: Prisma.EndPointCreateManyMonitoredHostInputEnvelope
  connect?: Prisma.EndPointWhereUniqueInput | Prisma.EndPointWhereUniqueInput[]
}

export type EndPointUpdateManyWithoutMonitoredHostNestedInput = {
  create?: Prisma.XOR<Prisma.EndPointCreateWithoutMonitoredHostInput, Prisma.EndPointUncheckedCreateWithoutMonitoredHostInput> | Prisma.EndPointCreateWithoutMonitoredHostInput[] | Prisma.EndPointUncheckedCreateWithoutMonitoredHostInput[]
  connectOrCreate?: Prisma.EndPointCreateOrConnectWithoutMonitoredHostInput | Prisma.EndPointCreateOrConnectWithoutMonitoredHostInput[]
  upsert?: Prisma.EndPointUpsertWithWhereUniqueWithoutMonitoredHostInput | Prisma.EndPointUpsertWithWhereUniqueWithoutMonitoredHostInput[]
  createMany?: Prisma.EndPointCreateManyMonitoredHostInputEnvelope
  set?: Prisma.EndPointWhereUniqueInput | Prisma.EndPointWhereUniqueInput[]
  disconnect?: Prisma.EndPointWhereUniqueInput | Prisma.EndPointWhereUniqueInput[]
  delete?: Prisma.EndPointWhereUniqueInput | Prisma.EndPointWhereUniqueInput[]
  connect?: Prisma.EndPointWhereUniqueInput | Prisma.EndPointWhereUniqueInput[]
  update?: Prisma.EndPointUpdateWithWhereUniqueWithoutMonitoredHostInput | Prisma.EndPointUpdateWithWhereUniqueWithoutMonitoredHostInput[]
  updateMany?: Prisma.EndPointUpdateManyWithWhereWithoutMonitoredHostInput | Prisma.EndPointUpdateManyWithWhereWithoutMonitoredHostInput[]
  deleteMany?: Prisma.EndPointScalarWhereInput | Prisma.EndPointScalarWhereInput[]
}

export type EndPointUncheckedUpdateManyWithoutMonitoredHostNestedInput = {
  create?: Prisma.XOR<Prisma.EndPointCreateWithoutMonitoredHostInput, Prisma.EndPointUncheckedCreateWithoutMonitoredHostInput> | Prisma.EndPointCreateWithoutMonitoredHostInput[] | Prisma.EndPointUncheckedCreateWithoutMonitoredHostInput[]
  connectOrCreate?: Prisma.EndPointCreateOrConnectWithoutMonitoredHostInput | Prisma.EndPointCreateOrConnectWithoutMonitoredHostInput[]
  upsert?: Prisma.EndPointUpsertWithWhereUniqueWithoutMonitoredHostInput | Prisma.EndPointUpsertWithWhereUniqueWithoutMonitoredHostInput[]
  createMany?: Prisma.EndPointCreateManyMonitoredHostInputEnvelope
  set?: Prisma.EndPointWhereUniqueInput | Prisma.EndPointWhereUniqueInput[]
  disconnect?: Prisma.EndPointWhereUniqueInput | Prisma.EndPointWhereUniqueInput[]
  delete?: Prisma.EndPointWhereUniqueInput | Prisma.EndPointWhereUniqueInput[]
  connect?: Prisma.EndPointWhereUniqueInput | Prisma.EndPointWhereUniqueInput[]
  update?: Prisma.EndPointUpdateWithWhereUniqueWithoutMonitoredHostInput | Prisma.EndPointUpdateWithWhereUniqueWithoutMonitoredHostInput[]
  updateMany?: Prisma.EndPointUpdateManyWithWhereWithoutMonitoredHostInput | Prisma.EndPointUpdateManyWithWhereWithoutMonitoredHostInput[]
  deleteMany?: Prisma.EndPointScalarWhereInput | Prisma.EndPointScalarWhereInput[]
}

export type EnumEndPointTypeFieldUpdateOperationsInput = {
  set?: $Enums.EndPointType
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type EndPointCreateNestedOneWithoutResultsInput = {
  create?: Prisma.XOR<Prisma.EndPointCreateWithoutResultsInput, Prisma.EndPointUncheckedCreateWithoutResultsInput>
  connectOrCreate?: Prisma.EndPointCreateOrConnectWithoutResultsInput
  connect?: Prisma.EndPointWhereUniqueInput
}

export type EndPointUpdateOneRequiredWithoutResultsNestedInput = {
  create?: Prisma.XOR<Prisma.EndPointCreateWithoutResultsInput, Prisma.EndPointUncheckedCreateWithoutResultsInput>
  connectOrCreate?: Prisma.EndPointCreateOrConnectWithoutResultsInput
  upsert?: Prisma.EndPointUpsertWithoutResultsInput
  connect?: Prisma.EndPointWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EndPointUpdateToOneWithWhereWithoutResultsInput, Prisma.EndPointUpdateWithoutResultsInput>, Prisma.EndPointUncheckedUpdateWithoutResultsInput>
}

export type EndPointCreateNestedOneWithoutHourlyStatsInput = {
  create?: Prisma.XOR<Prisma.EndPointCreateWithoutHourlyStatsInput, Prisma.EndPointUncheckedCreateWithoutHourlyStatsInput>
  connectOrCreate?: Prisma.EndPointCreateOrConnectWithoutHourlyStatsInput
  connect?: Prisma.EndPointWhereUniqueInput
}

export type EndPointUpdateOneRequiredWithoutHourlyStatsNestedInput = {
  create?: Prisma.XOR<Prisma.EndPointCreateWithoutHourlyStatsInput, Prisma.EndPointUncheckedCreateWithoutHourlyStatsInput>
  connectOrCreate?: Prisma.EndPointCreateOrConnectWithoutHourlyStatsInput
  upsert?: Prisma.EndPointUpsertWithoutHourlyStatsInput
  connect?: Prisma.EndPointWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EndPointUpdateToOneWithWhereWithoutHourlyStatsInput, Prisma.EndPointUpdateWithoutHourlyStatsInput>, Prisma.EndPointUncheckedUpdateWithoutHourlyStatsInput>
}

export type EndPointCreateNestedOneWithoutDailyStatsInput = {
  create?: Prisma.XOR<Prisma.EndPointCreateWithoutDailyStatsInput, Prisma.EndPointUncheckedCreateWithoutDailyStatsInput>
  connectOrCreate?: Prisma.EndPointCreateOrConnectWithoutDailyStatsInput
  connect?: Prisma.EndPointWhereUniqueInput
}

export type EndPointUpdateOneRequiredWithoutDailyStatsNestedInput = {
  create?: Prisma.XOR<Prisma.EndPointCreateWithoutDailyStatsInput, Prisma.EndPointUncheckedCreateWithoutDailyStatsInput>
  connectOrCreate?: Prisma.EndPointCreateOrConnectWithoutDailyStatsInput
  upsert?: Prisma.EndPointUpsertWithoutDailyStatsInput
  connect?: Prisma.EndPointWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EndPointUpdateToOneWithWhereWithoutDailyStatsInput, Prisma.EndPointUpdateWithoutDailyStatsInput>, Prisma.EndPointUncheckedUpdateWithoutDailyStatsInput>
}

export type EndPointCreateWithoutMonitoredHostInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  desc?: string | null
  type?: $Enums.EndPointType
  url?: string | null
  method?: string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: number | null
  bodyContentType?: string | null
  bodyContent?: string | null
  codeContent?: string | null
  intervalTime?: number | null
  enabled?: boolean
  results?: Prisma.ProbeResultCreateNestedManyWithoutEndPointInput
  hourlyStats?: Prisma.ProbeHourlyStatCreateNestedManyWithoutEndPointInput
  dailyStats?: Prisma.ProbeDailyStatCreateNestedManyWithoutEndPointInput
}

export type EndPointUncheckedCreateWithoutMonitoredHostInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  desc?: string | null
  type?: $Enums.EndPointType
  url?: string | null
  method?: string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: number | null
  bodyContentType?: string | null
  bodyContent?: string | null
  codeContent?: string | null
  intervalTime?: number | null
  enabled?: boolean
  results?: Prisma.ProbeResultUncheckedCreateNestedManyWithoutEndPointInput
  hourlyStats?: Prisma.ProbeHourlyStatUncheckedCreateNestedManyWithoutEndPointInput
  dailyStats?: Prisma.ProbeDailyStatUncheckedCreateNestedManyWithoutEndPointInput
}

export type EndPointCreateOrConnectWithoutMonitoredHostInput = {
  where: Prisma.EndPointWhereUniqueInput
  create: Prisma.XOR<Prisma.EndPointCreateWithoutMonitoredHostInput, Prisma.EndPointUncheckedCreateWithoutMonitoredHostInput>
}

export type EndPointCreateManyMonitoredHostInputEnvelope = {
  data: Prisma.EndPointCreateManyMonitoredHostInput | Prisma.EndPointCreateManyMonitoredHostInput[]
}

export type EndPointUpsertWithWhereUniqueWithoutMonitoredHostInput = {
  where: Prisma.EndPointWhereUniqueInput
  update: Prisma.XOR<Prisma.EndPointUpdateWithoutMonitoredHostInput, Prisma.EndPointUncheckedUpdateWithoutMonitoredHostInput>
  create: Prisma.XOR<Prisma.EndPointCreateWithoutMonitoredHostInput, Prisma.EndPointUncheckedCreateWithoutMonitoredHostInput>
}

export type EndPointUpdateWithWhereUniqueWithoutMonitoredHostInput = {
  where: Prisma.EndPointWhereUniqueInput
  data: Prisma.XOR<Prisma.EndPointUpdateWithoutMonitoredHostInput, Prisma.EndPointUncheckedUpdateWithoutMonitoredHostInput>
}

export type EndPointUpdateManyWithWhereWithoutMonitoredHostInput = {
  where: Prisma.EndPointScalarWhereInput
  data: Prisma.XOR<Prisma.EndPointUpdateManyMutationInput, Prisma.EndPointUncheckedUpdateManyWithoutMonitoredHostInput>
}

export type EndPointScalarWhereInput = {
  AND?: Prisma.EndPointScalarWhereInput | Prisma.EndPointScalarWhereInput[]
  OR?: Prisma.EndPointScalarWhereInput[]
  NOT?: Prisma.EndPointScalarWhereInput | Prisma.EndPointScalarWhereInput[]
  id?: Prisma.StringFilter<"EndPoint"> | string
  createdAt?: Prisma.DateTimeFilter<"EndPoint"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"EndPoint"> | Date | string
  hostId?: Prisma.StringFilter<"EndPoint"> | string
  name?: Prisma.StringFilter<"EndPoint"> | string
  desc?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  type?: Prisma.EnumEndPointTypeFilter<"EndPoint"> | $Enums.EndPointType
  url?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  method?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  headers?: Prisma.JsonNullableFilter<"EndPoint">
  timeout?: Prisma.IntNullableFilter<"EndPoint"> | number | null
  bodyContentType?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  bodyContent?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  codeContent?: Prisma.StringNullableFilter<"EndPoint"> | string | null
  intervalTime?: Prisma.IntNullableFilter<"EndPoint"> | number | null
  enabled?: Prisma.BoolFilter<"EndPoint"> | boolean
}

export type EndPointCreateWithoutResultsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  desc?: string | null
  type?: $Enums.EndPointType
  url?: string | null
  method?: string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: number | null
  bodyContentType?: string | null
  bodyContent?: string | null
  codeContent?: string | null
  intervalTime?: number | null
  enabled?: boolean
  hourlyStats?: Prisma.ProbeHourlyStatCreateNestedManyWithoutEndPointInput
  dailyStats?: Prisma.ProbeDailyStatCreateNestedManyWithoutEndPointInput
  monitoredHost: Prisma.MonitoredHostCreateNestedOneWithoutEndpointsInput
}

export type EndPointUncheckedCreateWithoutResultsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  hostId: string
  name: string
  desc?: string | null
  type?: $Enums.EndPointType
  url?: string | null
  method?: string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: number | null
  bodyContentType?: string | null
  bodyContent?: string | null
  codeContent?: string | null
  intervalTime?: number | null
  enabled?: boolean
  hourlyStats?: Prisma.ProbeHourlyStatUncheckedCreateNestedManyWithoutEndPointInput
  dailyStats?: Prisma.ProbeDailyStatUncheckedCreateNestedManyWithoutEndPointInput
}

export type EndPointCreateOrConnectWithoutResultsInput = {
  where: Prisma.EndPointWhereUniqueInput
  create: Prisma.XOR<Prisma.EndPointCreateWithoutResultsInput, Prisma.EndPointUncheckedCreateWithoutResultsInput>
}

export type EndPointUpsertWithoutResultsInput = {
  update: Prisma.XOR<Prisma.EndPointUpdateWithoutResultsInput, Prisma.EndPointUncheckedUpdateWithoutResultsInput>
  create: Prisma.XOR<Prisma.EndPointCreateWithoutResultsInput, Prisma.EndPointUncheckedCreateWithoutResultsInput>
  where?: Prisma.EndPointWhereInput
}

export type EndPointUpdateToOneWithWhereWithoutResultsInput = {
  where?: Prisma.EndPointWhereInput
  data: Prisma.XOR<Prisma.EndPointUpdateWithoutResultsInput, Prisma.EndPointUncheckedUpdateWithoutResultsInput>
}

export type EndPointUpdateWithoutResultsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumEndPointTypeFieldUpdateOperationsInput | $Enums.EndPointType
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bodyContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  codeContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervalTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hourlyStats?: Prisma.ProbeHourlyStatUpdateManyWithoutEndPointNestedInput
  dailyStats?: Prisma.ProbeDailyStatUpdateManyWithoutEndPointNestedInput
  monitoredHost?: Prisma.MonitoredHostUpdateOneRequiredWithoutEndpointsNestedInput
}

export type EndPointUncheckedUpdateWithoutResultsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hostId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumEndPointTypeFieldUpdateOperationsInput | $Enums.EndPointType
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bodyContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  codeContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervalTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hourlyStats?: Prisma.ProbeHourlyStatUncheckedUpdateManyWithoutEndPointNestedInput
  dailyStats?: Prisma.ProbeDailyStatUncheckedUpdateManyWithoutEndPointNestedInput
}

export type EndPointCreateWithoutHourlyStatsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  desc?: string | null
  type?: $Enums.EndPointType
  url?: string | null
  method?: string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: number | null
  bodyContentType?: string | null
  bodyContent?: string | null
  codeContent?: string | null
  intervalTime?: number | null
  enabled?: boolean
  results?: Prisma.ProbeResultCreateNestedManyWithoutEndPointInput
  dailyStats?: Prisma.ProbeDailyStatCreateNestedManyWithoutEndPointInput
  monitoredHost: Prisma.MonitoredHostCreateNestedOneWithoutEndpointsInput
}

export type EndPointUncheckedCreateWithoutHourlyStatsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  hostId: string
  name: string
  desc?: string | null
  type?: $Enums.EndPointType
  url?: string | null
  method?: string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: number | null
  bodyContentType?: string | null
  bodyContent?: string | null
  codeContent?: string | null
  intervalTime?: number | null
  enabled?: boolean
  results?: Prisma.ProbeResultUncheckedCreateNestedManyWithoutEndPointInput
  dailyStats?: Prisma.ProbeDailyStatUncheckedCreateNestedManyWithoutEndPointInput
}

export type EndPointCreateOrConnectWithoutHourlyStatsInput = {
  where: Prisma.EndPointWhereUniqueInput
  create: Prisma.XOR<Prisma.EndPointCreateWithoutHourlyStatsInput, Prisma.EndPointUncheckedCreateWithoutHourlyStatsInput>
}

export type EndPointUpsertWithoutHourlyStatsInput = {
  update: Prisma.XOR<Prisma.EndPointUpdateWithoutHourlyStatsInput, Prisma.EndPointUncheckedUpdateWithoutHourlyStatsInput>
  create: Prisma.XOR<Prisma.EndPointCreateWithoutHourlyStatsInput, Prisma.EndPointUncheckedCreateWithoutHourlyStatsInput>
  where?: Prisma.EndPointWhereInput
}

export type EndPointUpdateToOneWithWhereWithoutHourlyStatsInput = {
  where?: Prisma.EndPointWhereInput
  data: Prisma.XOR<Prisma.EndPointUpdateWithoutHourlyStatsInput, Prisma.EndPointUncheckedUpdateWithoutHourlyStatsInput>
}

export type EndPointUpdateWithoutHourlyStatsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumEndPointTypeFieldUpdateOperationsInput | $Enums.EndPointType
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bodyContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  codeContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervalTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  results?: Prisma.ProbeResultUpdateManyWithoutEndPointNestedInput
  dailyStats?: Prisma.ProbeDailyStatUpdateManyWithoutEndPointNestedInput
  monitoredHost?: Prisma.MonitoredHostUpdateOneRequiredWithoutEndpointsNestedInput
}

export type EndPointUncheckedUpdateWithoutHourlyStatsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hostId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumEndPointTypeFieldUpdateOperationsInput | $Enums.EndPointType
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bodyContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  codeContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervalTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  results?: Prisma.ProbeResultUncheckedUpdateManyWithoutEndPointNestedInput
  dailyStats?: Prisma.ProbeDailyStatUncheckedUpdateManyWithoutEndPointNestedInput
}

export type EndPointCreateWithoutDailyStatsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  desc?: string | null
  type?: $Enums.EndPointType
  url?: string | null
  method?: string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: number | null
  bodyContentType?: string | null
  bodyContent?: string | null
  codeContent?: string | null
  intervalTime?: number | null
  enabled?: boolean
  results?: Prisma.ProbeResultCreateNestedManyWithoutEndPointInput
  hourlyStats?: Prisma.ProbeHourlyStatCreateNestedManyWithoutEndPointInput
  monitoredHost: Prisma.MonitoredHostCreateNestedOneWithoutEndpointsInput
}

export type EndPointUncheckedCreateWithoutDailyStatsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  hostId: string
  name: string
  desc?: string | null
  type?: $Enums.EndPointType
  url?: string | null
  method?: string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: number | null
  bodyContentType?: string | null
  bodyContent?: string | null
  codeContent?: string | null
  intervalTime?: number | null
  enabled?: boolean
  results?: Prisma.ProbeResultUncheckedCreateNestedManyWithoutEndPointInput
  hourlyStats?: Prisma.ProbeHourlyStatUncheckedCreateNestedManyWithoutEndPointInput
}

export type EndPointCreateOrConnectWithoutDailyStatsInput = {
  where: Prisma.EndPointWhereUniqueInput
  create: Prisma.XOR<Prisma.EndPointCreateWithoutDailyStatsInput, Prisma.EndPointUncheckedCreateWithoutDailyStatsInput>
}

export type EndPointUpsertWithoutDailyStatsInput = {
  update: Prisma.XOR<Prisma.EndPointUpdateWithoutDailyStatsInput, Prisma.EndPointUncheckedUpdateWithoutDailyStatsInput>
  create: Prisma.XOR<Prisma.EndPointCreateWithoutDailyStatsInput, Prisma.EndPointUncheckedCreateWithoutDailyStatsInput>
  where?: Prisma.EndPointWhereInput
}

export type EndPointUpdateToOneWithWhereWithoutDailyStatsInput = {
  where?: Prisma.EndPointWhereInput
  data: Prisma.XOR<Prisma.EndPointUpdateWithoutDailyStatsInput, Prisma.EndPointUncheckedUpdateWithoutDailyStatsInput>
}

export type EndPointUpdateWithoutDailyStatsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumEndPointTypeFieldUpdateOperationsInput | $Enums.EndPointType
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bodyContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  codeContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervalTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  results?: Prisma.ProbeResultUpdateManyWithoutEndPointNestedInput
  hourlyStats?: Prisma.ProbeHourlyStatUpdateManyWithoutEndPointNestedInput
  monitoredHost?: Prisma.MonitoredHostUpdateOneRequiredWithoutEndpointsNestedInput
}

export type EndPointUncheckedUpdateWithoutDailyStatsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  hostId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumEndPointTypeFieldUpdateOperationsInput | $Enums.EndPointType
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bodyContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  codeContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervalTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  results?: Prisma.ProbeResultUncheckedUpdateManyWithoutEndPointNestedInput
  hourlyStats?: Prisma.ProbeHourlyStatUncheckedUpdateManyWithoutEndPointNestedInput
}

export type EndPointCreateManyMonitoredHostInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  desc?: string | null
  type?: $Enums.EndPointType
  url?: string | null
  method?: string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: number | null
  bodyContentType?: string | null
  bodyContent?: string | null
  codeContent?: string | null
  intervalTime?: number | null
  enabled?: boolean
}

export type EndPointUpdateWithoutMonitoredHostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumEndPointTypeFieldUpdateOperationsInput | $Enums.EndPointType
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bodyContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  codeContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervalTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  results?: Prisma.ProbeResultUpdateManyWithoutEndPointNestedInput
  hourlyStats?: Prisma.ProbeHourlyStatUpdateManyWithoutEndPointNestedInput
  dailyStats?: Prisma.ProbeDailyStatUpdateManyWithoutEndPointNestedInput
}

export type EndPointUncheckedUpdateWithoutMonitoredHostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumEndPointTypeFieldUpdateOperationsInput | $Enums.EndPointType
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bodyContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  codeContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervalTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  results?: Prisma.ProbeResultUncheckedUpdateManyWithoutEndPointNestedInput
  hourlyStats?: Prisma.ProbeHourlyStatUncheckedUpdateManyWithoutEndPointNestedInput
  dailyStats?: Prisma.ProbeDailyStatUncheckedUpdateManyWithoutEndPointNestedInput
}

export type EndPointUncheckedUpdateManyWithoutMonitoredHostInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  desc?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumEndPointTypeFieldUpdateOperationsInput | $Enums.EndPointType
  url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  method?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  timeout?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bodyContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bodyContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  codeContent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervalTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type EndPointCountOutputType
 */

export type EndPointCountOutputType = {
  results: number
  hourlyStats: number
  dailyStats: number
}

export type EndPointCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  results?: boolean | EndPointCountOutputTypeCountResultsArgs
  hourlyStats?: boolean | EndPointCountOutputTypeCountHourlyStatsArgs
  dailyStats?: boolean | EndPointCountOutputTypeCountDailyStatsArgs
}

/**
 * EndPointCountOutputType without action
 */
export type EndPointCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndPointCountOutputType
   */
  select?: Prisma.EndPointCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EndPointCountOutputType without action
 */
export type EndPointCountOutputTypeCountResultsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProbeResultWhereInput
}

/**
 * EndPointCountOutputType without action
 */
export type EndPointCountOutputTypeCountHourlyStatsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProbeHourlyStatWhereInput
}

/**
 * EndPointCountOutputType without action
 */
export type EndPointCountOutputTypeCountDailyStatsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProbeDailyStatWhereInput
}


export type EndPointSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  hostId?: boolean
  name?: boolean
  desc?: boolean
  type?: boolean
  url?: boolean
  method?: boolean
  headers?: boolean
  timeout?: boolean
  bodyContentType?: boolean
  bodyContent?: boolean
  codeContent?: boolean
  intervalTime?: boolean
  enabled?: boolean
  results?: boolean | Prisma.EndPoint$resultsArgs<ExtArgs>
  hourlyStats?: boolean | Prisma.EndPoint$hourlyStatsArgs<ExtArgs>
  dailyStats?: boolean | Prisma.EndPoint$dailyStatsArgs<ExtArgs>
  monitoredHost?: boolean | Prisma.MonitoredHostDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.EndPointCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["endPoint"]>

export type EndPointSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  hostId?: boolean
  name?: boolean
  desc?: boolean
  type?: boolean
  url?: boolean
  method?: boolean
  headers?: boolean
  timeout?: boolean
  bodyContentType?: boolean
  bodyContent?: boolean
  codeContent?: boolean
  intervalTime?: boolean
  enabled?: boolean
  monitoredHost?: boolean | Prisma.MonitoredHostDefaultArgs<ExtArgs>
}, ExtArgs["result"]["endPoint"]>

export type EndPointSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  hostId?: boolean
  name?: boolean
  desc?: boolean
  type?: boolean
  url?: boolean
  method?: boolean
  headers?: boolean
  timeout?: boolean
  bodyContentType?: boolean
  bodyContent?: boolean
  codeContent?: boolean
  intervalTime?: boolean
  enabled?: boolean
  monitoredHost?: boolean | Prisma.MonitoredHostDefaultArgs<ExtArgs>
}, ExtArgs["result"]["endPoint"]>

export type EndPointSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  hostId?: boolean
  name?: boolean
  desc?: boolean
  type?: boolean
  url?: boolean
  method?: boolean
  headers?: boolean
  timeout?: boolean
  bodyContentType?: boolean
  bodyContent?: boolean
  codeContent?: boolean
  intervalTime?: boolean
  enabled?: boolean
}

export type EndPointOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "hostId" | "name" | "desc" | "type" | "url" | "method" | "headers" | "timeout" | "bodyContentType" | "bodyContent" | "codeContent" | "intervalTime" | "enabled", ExtArgs["result"]["endPoint"]>
export type EndPointInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  results?: boolean | Prisma.EndPoint$resultsArgs<ExtArgs>
  hourlyStats?: boolean | Prisma.EndPoint$hourlyStatsArgs<ExtArgs>
  dailyStats?: boolean | Prisma.EndPoint$dailyStatsArgs<ExtArgs>
  monitoredHost?: boolean | Prisma.MonitoredHostDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.EndPointCountOutputTypeDefaultArgs<ExtArgs>
}
export type EndPointIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  monitoredHost?: boolean | Prisma.MonitoredHostDefaultArgs<ExtArgs>
}
export type EndPointIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  monitoredHost?: boolean | Prisma.MonitoredHostDefaultArgs<ExtArgs>
}

export type $EndPointPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EndPoint"
  objects: {
    results: Prisma.$ProbeResultPayload<ExtArgs>[]
    hourlyStats: Prisma.$ProbeHourlyStatPayload<ExtArgs>[]
    dailyStats: Prisma.$ProbeDailyStatPayload<ExtArgs>[]
    monitoredHost: Prisma.$MonitoredHostPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    hostId: string
    name: string
    desc: string | null
    type: $Enums.EndPointType
    url: string | null
    method: string | null
    headers: runtime.JsonValue | null
    timeout: number | null
    bodyContentType: string | null
    bodyContent: string | null
    codeContent: string | null
    intervalTime: number | null
    enabled: boolean
  }, ExtArgs["result"]["endPoint"]>
  composites: {}
}

export type EndPointGetPayload<S extends boolean | null | undefined | EndPointDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EndPointPayload, S>

export type EndPointCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EndPointFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EndPointCountAggregateInputType | true
  }

export interface EndPointDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EndPoint'], meta: { name: 'EndPoint' } }
  /**
   * Find zero or one EndPoint that matches the filter.
   * @param {EndPointFindUniqueArgs} args - Arguments to find a EndPoint
   * @example
   * // Get one EndPoint
   * const endPoint = await prisma.endPoint.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EndPointFindUniqueArgs>(args: Prisma.SelectSubset<T, EndPointFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EndPointClient<runtime.Types.Result.GetResult<Prisma.$EndPointPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EndPoint that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EndPointFindUniqueOrThrowArgs} args - Arguments to find a EndPoint
   * @example
   * // Get one EndPoint
   * const endPoint = await prisma.endPoint.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EndPointFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EndPointFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EndPointClient<runtime.Types.Result.GetResult<Prisma.$EndPointPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EndPoint that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndPointFindFirstArgs} args - Arguments to find a EndPoint
   * @example
   * // Get one EndPoint
   * const endPoint = await prisma.endPoint.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EndPointFindFirstArgs>(args?: Prisma.SelectSubset<T, EndPointFindFirstArgs<ExtArgs>>): Prisma.Prisma__EndPointClient<runtime.Types.Result.GetResult<Prisma.$EndPointPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EndPoint that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndPointFindFirstOrThrowArgs} args - Arguments to find a EndPoint
   * @example
   * // Get one EndPoint
   * const endPoint = await prisma.endPoint.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EndPointFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EndPointFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EndPointClient<runtime.Types.Result.GetResult<Prisma.$EndPointPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EndPoints that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndPointFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EndPoints
   * const endPoints = await prisma.endPoint.findMany()
   * 
   * // Get first 10 EndPoints
   * const endPoints = await prisma.endPoint.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const endPointWithIdOnly = await prisma.endPoint.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EndPointFindManyArgs>(args?: Prisma.SelectSubset<T, EndPointFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EndPointPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EndPoint.
   * @param {EndPointCreateArgs} args - Arguments to create a EndPoint.
   * @example
   * // Create one EndPoint
   * const EndPoint = await prisma.endPoint.create({
   *   data: {
   *     // ... data to create a EndPoint
   *   }
   * })
   * 
   */
  create<T extends EndPointCreateArgs>(args: Prisma.SelectSubset<T, EndPointCreateArgs<ExtArgs>>): Prisma.Prisma__EndPointClient<runtime.Types.Result.GetResult<Prisma.$EndPointPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EndPoints.
   * @param {EndPointCreateManyArgs} args - Arguments to create many EndPoints.
   * @example
   * // Create many EndPoints
   * const endPoint = await prisma.endPoint.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EndPointCreateManyArgs>(args?: Prisma.SelectSubset<T, EndPointCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EndPoints and returns the data saved in the database.
   * @param {EndPointCreateManyAndReturnArgs} args - Arguments to create many EndPoints.
   * @example
   * // Create many EndPoints
   * const endPoint = await prisma.endPoint.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EndPoints and only return the `id`
   * const endPointWithIdOnly = await prisma.endPoint.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EndPointCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EndPointCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EndPointPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EndPoint.
   * @param {EndPointDeleteArgs} args - Arguments to delete one EndPoint.
   * @example
   * // Delete one EndPoint
   * const EndPoint = await prisma.endPoint.delete({
   *   where: {
   *     // ... filter to delete one EndPoint
   *   }
   * })
   * 
   */
  delete<T extends EndPointDeleteArgs>(args: Prisma.SelectSubset<T, EndPointDeleteArgs<ExtArgs>>): Prisma.Prisma__EndPointClient<runtime.Types.Result.GetResult<Prisma.$EndPointPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EndPoint.
   * @param {EndPointUpdateArgs} args - Arguments to update one EndPoint.
   * @example
   * // Update one EndPoint
   * const endPoint = await prisma.endPoint.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EndPointUpdateArgs>(args: Prisma.SelectSubset<T, EndPointUpdateArgs<ExtArgs>>): Prisma.Prisma__EndPointClient<runtime.Types.Result.GetResult<Prisma.$EndPointPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EndPoints.
   * @param {EndPointDeleteManyArgs} args - Arguments to filter EndPoints to delete.
   * @example
   * // Delete a few EndPoints
   * const { count } = await prisma.endPoint.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EndPointDeleteManyArgs>(args?: Prisma.SelectSubset<T, EndPointDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EndPoints.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndPointUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EndPoints
   * const endPoint = await prisma.endPoint.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EndPointUpdateManyArgs>(args: Prisma.SelectSubset<T, EndPointUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EndPoints and returns the data updated in the database.
   * @param {EndPointUpdateManyAndReturnArgs} args - Arguments to update many EndPoints.
   * @example
   * // Update many EndPoints
   * const endPoint = await prisma.endPoint.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EndPoints and only return the `id`
   * const endPointWithIdOnly = await prisma.endPoint.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EndPointUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EndPointUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EndPointPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EndPoint.
   * @param {EndPointUpsertArgs} args - Arguments to update or create a EndPoint.
   * @example
   * // Update or create a EndPoint
   * const endPoint = await prisma.endPoint.upsert({
   *   create: {
   *     // ... data to create a EndPoint
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EndPoint we want to update
   *   }
   * })
   */
  upsert<T extends EndPointUpsertArgs>(args: Prisma.SelectSubset<T, EndPointUpsertArgs<ExtArgs>>): Prisma.Prisma__EndPointClient<runtime.Types.Result.GetResult<Prisma.$EndPointPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EndPoints.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndPointCountArgs} args - Arguments to filter EndPoints to count.
   * @example
   * // Count the number of EndPoints
   * const count = await prisma.endPoint.count({
   *   where: {
   *     // ... the filter for the EndPoints we want to count
   *   }
   * })
  **/
  count<T extends EndPointCountArgs>(
    args?: Prisma.Subset<T, EndPointCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EndPointCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EndPoint.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndPointAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EndPointAggregateArgs>(args: Prisma.Subset<T, EndPointAggregateArgs>): Prisma.PrismaPromise<GetEndPointAggregateType<T>>

  /**
   * Group by EndPoint.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EndPointGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EndPointGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EndPointGroupByArgs['orderBy'] }
      : { orderBy?: EndPointGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EndPointGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEndPointGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EndPoint model
 */
readonly fields: EndPointFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EndPoint.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EndPointClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  results<T extends Prisma.EndPoint$resultsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EndPoint$resultsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProbeResultPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  hourlyStats<T extends Prisma.EndPoint$hourlyStatsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EndPoint$hourlyStatsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProbeHourlyStatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  dailyStats<T extends Prisma.EndPoint$dailyStatsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EndPoint$dailyStatsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProbeDailyStatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  monitoredHost<T extends Prisma.MonitoredHostDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MonitoredHostDefaultArgs<ExtArgs>>): Prisma.Prisma__MonitoredHostClient<runtime.Types.Result.GetResult<Prisma.$MonitoredHostPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EndPoint model
 */
export interface EndPointFieldRefs {
  readonly id: Prisma.FieldRef<"EndPoint", 'String'>
  readonly createdAt: Prisma.FieldRef<"EndPoint", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"EndPoint", 'DateTime'>
  readonly hostId: Prisma.FieldRef<"EndPoint", 'String'>
  readonly name: Prisma.FieldRef<"EndPoint", 'String'>
  readonly desc: Prisma.FieldRef<"EndPoint", 'String'>
  readonly type: Prisma.FieldRef<"EndPoint", 'EndPointType'>
  readonly url: Prisma.FieldRef<"EndPoint", 'String'>
  readonly method: Prisma.FieldRef<"EndPoint", 'String'>
  readonly headers: Prisma.FieldRef<"EndPoint", 'Json'>
  readonly timeout: Prisma.FieldRef<"EndPoint", 'Int'>
  readonly bodyContentType: Prisma.FieldRef<"EndPoint", 'String'>
  readonly bodyContent: Prisma.FieldRef<"EndPoint", 'String'>
  readonly codeContent: Prisma.FieldRef<"EndPoint", 'String'>
  readonly intervalTime: Prisma.FieldRef<"EndPoint", 'Int'>
  readonly enabled: Prisma.FieldRef<"EndPoint", 'Boolean'>
}
    

// Custom InputTypes
/**
 * EndPoint findUnique
 */
export type EndPointFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndPoint
   */
  select?: Prisma.EndPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndPoint
   */
  omit?: Prisma.EndPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndPointInclude<ExtArgs> | null
  /**
   * Filter, which EndPoint to fetch.
   */
  where: Prisma.EndPointWhereUniqueInput
}

/**
 * EndPoint findUniqueOrThrow
 */
export type EndPointFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndPoint
   */
  select?: Prisma.EndPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndPoint
   */
  omit?: Prisma.EndPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndPointInclude<ExtArgs> | null
  /**
   * Filter, which EndPoint to fetch.
   */
  where: Prisma.EndPointWhereUniqueInput
}

/**
 * EndPoint findFirst
 */
export type EndPointFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndPoint
   */
  select?: Prisma.EndPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndPoint
   */
  omit?: Prisma.EndPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndPointInclude<ExtArgs> | null
  /**
   * Filter, which EndPoint to fetch.
   */
  where?: Prisma.EndPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EndPoints to fetch.
   */
  orderBy?: Prisma.EndPointOrderByWithRelationInput | Prisma.EndPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EndPoints.
   */
  cursor?: Prisma.EndPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EndPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EndPoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EndPoints.
   */
  distinct?: Prisma.EndPointScalarFieldEnum | Prisma.EndPointScalarFieldEnum[]
}

/**
 * EndPoint findFirstOrThrow
 */
export type EndPointFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndPoint
   */
  select?: Prisma.EndPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndPoint
   */
  omit?: Prisma.EndPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndPointInclude<ExtArgs> | null
  /**
   * Filter, which EndPoint to fetch.
   */
  where?: Prisma.EndPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EndPoints to fetch.
   */
  orderBy?: Prisma.EndPointOrderByWithRelationInput | Prisma.EndPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EndPoints.
   */
  cursor?: Prisma.EndPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EndPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EndPoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EndPoints.
   */
  distinct?: Prisma.EndPointScalarFieldEnum | Prisma.EndPointScalarFieldEnum[]
}

/**
 * EndPoint findMany
 */
export type EndPointFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndPoint
   */
  select?: Prisma.EndPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndPoint
   */
  omit?: Prisma.EndPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndPointInclude<ExtArgs> | null
  /**
   * Filter, which EndPoints to fetch.
   */
  where?: Prisma.EndPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EndPoints to fetch.
   */
  orderBy?: Prisma.EndPointOrderByWithRelationInput | Prisma.EndPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EndPoints.
   */
  cursor?: Prisma.EndPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EndPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EndPoints.
   */
  skip?: number
  distinct?: Prisma.EndPointScalarFieldEnum | Prisma.EndPointScalarFieldEnum[]
}

/**
 * EndPoint create
 */
export type EndPointCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndPoint
   */
  select?: Prisma.EndPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndPoint
   */
  omit?: Prisma.EndPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndPointInclude<ExtArgs> | null
  /**
   * The data needed to create a EndPoint.
   */
  data: Prisma.XOR<Prisma.EndPointCreateInput, Prisma.EndPointUncheckedCreateInput>
}

/**
 * EndPoint createMany
 */
export type EndPointCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EndPoints.
   */
  data: Prisma.EndPointCreateManyInput | Prisma.EndPointCreateManyInput[]
}

/**
 * EndPoint createManyAndReturn
 */
export type EndPointCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndPoint
   */
  select?: Prisma.EndPointSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EndPoint
   */
  omit?: Prisma.EndPointOmit<ExtArgs> | null
  /**
   * The data used to create many EndPoints.
   */
  data: Prisma.EndPointCreateManyInput | Prisma.EndPointCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndPointIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EndPoint update
 */
export type EndPointUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndPoint
   */
  select?: Prisma.EndPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndPoint
   */
  omit?: Prisma.EndPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndPointInclude<ExtArgs> | null
  /**
   * The data needed to update a EndPoint.
   */
  data: Prisma.XOR<Prisma.EndPointUpdateInput, Prisma.EndPointUncheckedUpdateInput>
  /**
   * Choose, which EndPoint to update.
   */
  where: Prisma.EndPointWhereUniqueInput
}

/**
 * EndPoint updateMany
 */
export type EndPointUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EndPoints.
   */
  data: Prisma.XOR<Prisma.EndPointUpdateManyMutationInput, Prisma.EndPointUncheckedUpdateManyInput>
  /**
   * Filter which EndPoints to update
   */
  where?: Prisma.EndPointWhereInput
  /**
   * Limit how many EndPoints to update.
   */
  limit?: number
}

/**
 * EndPoint updateManyAndReturn
 */
export type EndPointUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndPoint
   */
  select?: Prisma.EndPointSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EndPoint
   */
  omit?: Prisma.EndPointOmit<ExtArgs> | null
  /**
   * The data used to update EndPoints.
   */
  data: Prisma.XOR<Prisma.EndPointUpdateManyMutationInput, Prisma.EndPointUncheckedUpdateManyInput>
  /**
   * Filter which EndPoints to update
   */
  where?: Prisma.EndPointWhereInput
  /**
   * Limit how many EndPoints to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndPointIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EndPoint upsert
 */
export type EndPointUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndPoint
   */
  select?: Prisma.EndPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndPoint
   */
  omit?: Prisma.EndPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndPointInclude<ExtArgs> | null
  /**
   * The filter to search for the EndPoint to update in case it exists.
   */
  where: Prisma.EndPointWhereUniqueInput
  /**
   * In case the EndPoint found by the `where` argument doesn't exist, create a new EndPoint with this data.
   */
  create: Prisma.XOR<Prisma.EndPointCreateInput, Prisma.EndPointUncheckedCreateInput>
  /**
   * In case the EndPoint was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EndPointUpdateInput, Prisma.EndPointUncheckedUpdateInput>
}

/**
 * EndPoint delete
 */
export type EndPointDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndPoint
   */
  select?: Prisma.EndPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndPoint
   */
  omit?: Prisma.EndPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndPointInclude<ExtArgs> | null
  /**
   * Filter which EndPoint to delete.
   */
  where: Prisma.EndPointWhereUniqueInput
}

/**
 * EndPoint deleteMany
 */
export type EndPointDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EndPoints to delete
   */
  where?: Prisma.EndPointWhereInput
  /**
   * Limit how many EndPoints to delete.
   */
  limit?: number
}

/**
 * EndPoint.results
 */
export type EndPoint$resultsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProbeResult
   */
  select?: Prisma.ProbeResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProbeResult
   */
  omit?: Prisma.ProbeResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProbeResultInclude<ExtArgs> | null
  where?: Prisma.ProbeResultWhereInput
  orderBy?: Prisma.ProbeResultOrderByWithRelationInput | Prisma.ProbeResultOrderByWithRelationInput[]
  cursor?: Prisma.ProbeResultWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProbeResultScalarFieldEnum | Prisma.ProbeResultScalarFieldEnum[]
}

/**
 * EndPoint.hourlyStats
 */
export type EndPoint$hourlyStatsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProbeHourlyStat
   */
  select?: Prisma.ProbeHourlyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProbeHourlyStat
   */
  omit?: Prisma.ProbeHourlyStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProbeHourlyStatInclude<ExtArgs> | null
  where?: Prisma.ProbeHourlyStatWhereInput
  orderBy?: Prisma.ProbeHourlyStatOrderByWithRelationInput | Prisma.ProbeHourlyStatOrderByWithRelationInput[]
  cursor?: Prisma.ProbeHourlyStatWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProbeHourlyStatScalarFieldEnum | Prisma.ProbeHourlyStatScalarFieldEnum[]
}

/**
 * EndPoint.dailyStats
 */
export type EndPoint$dailyStatsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProbeDailyStat
   */
  select?: Prisma.ProbeDailyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProbeDailyStat
   */
  omit?: Prisma.ProbeDailyStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProbeDailyStatInclude<ExtArgs> | null
  where?: Prisma.ProbeDailyStatWhereInput
  orderBy?: Prisma.ProbeDailyStatOrderByWithRelationInput | Prisma.ProbeDailyStatOrderByWithRelationInput[]
  cursor?: Prisma.ProbeDailyStatWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProbeDailyStatScalarFieldEnum | Prisma.ProbeDailyStatScalarFieldEnum[]
}

/**
 * EndPoint without action
 */
export type EndPointDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EndPoint
   */
  select?: Prisma.EndPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EndPoint
   */
  omit?: Prisma.EndPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EndPointInclude<ExtArgs> | null
}
