
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NotificationChannel` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model NotificationChannel
 * 
 */
export type NotificationChannelModel = runtime.Types.Result.DefaultSelection<Prisma.$NotificationChannelPayload>

export type AggregateNotificationChannel = {
  _count: NotificationChannelCountAggregateOutputType | null
  _min: NotificationChannelMinAggregateOutputType | null
  _max: NotificationChannelMaxAggregateOutputType | null
}

export type NotificationChannelMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  name: string | null
  webhookUrl: string | null
  bodyTemplate: string | null
  enabled: boolean | null
}

export type NotificationChannelMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  name: string | null
  webhookUrl: string | null
  bodyTemplate: string | null
  enabled: boolean | null
}

export type NotificationChannelCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  name: number
  webhookUrl: number
  headers: number
  bodyTemplate: number
  enabled: number
  _all: number
}


export type NotificationChannelMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  name?: true
  webhookUrl?: true
  bodyTemplate?: true
  enabled?: true
}

export type NotificationChannelMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  name?: true
  webhookUrl?: true
  bodyTemplate?: true
  enabled?: true
}

export type NotificationChannelCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  name?: true
  webhookUrl?: true
  headers?: true
  bodyTemplate?: true
  enabled?: true
  _all?: true
}

export type NotificationChannelAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NotificationChannel to aggregate.
   */
  where?: Prisma.NotificationChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NotificationChannels to fetch.
   */
  orderBy?: Prisma.NotificationChannelOrderByWithRelationInput | Prisma.NotificationChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NotificationChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NotificationChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NotificationChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NotificationChannels
  **/
  _count?: true | NotificationChannelCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NotificationChannelMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NotificationChannelMaxAggregateInputType
}

export type GetNotificationChannelAggregateType<T extends NotificationChannelAggregateArgs> = {
      [P in keyof T & keyof AggregateNotificationChannel]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNotificationChannel[P]>
    : Prisma.GetScalarType<T[P], AggregateNotificationChannel[P]>
}




export type NotificationChannelGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NotificationChannelWhereInput
  orderBy?: Prisma.NotificationChannelOrderByWithAggregationInput | Prisma.NotificationChannelOrderByWithAggregationInput[]
  by: Prisma.NotificationChannelScalarFieldEnum[] | Prisma.NotificationChannelScalarFieldEnum
  having?: Prisma.NotificationChannelScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NotificationChannelCountAggregateInputType | true
  _min?: NotificationChannelMinAggregateInputType
  _max?: NotificationChannelMaxAggregateInputType
}

export type NotificationChannelGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  name: string
  webhookUrl: string
  headers: runtime.JsonValue | null
  bodyTemplate: string
  enabled: boolean
  _count: NotificationChannelCountAggregateOutputType | null
  _min: NotificationChannelMinAggregateOutputType | null
  _max: NotificationChannelMaxAggregateOutputType | null
}

type GetNotificationChannelGroupByPayload<T extends NotificationChannelGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NotificationChannelGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NotificationChannelGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NotificationChannelGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NotificationChannelGroupByOutputType[P]>
      }
    >
  >



export type NotificationChannelWhereInput = {
  AND?: Prisma.NotificationChannelWhereInput | Prisma.NotificationChannelWhereInput[]
  OR?: Prisma.NotificationChannelWhereInput[]
  NOT?: Prisma.NotificationChannelWhereInput | Prisma.NotificationChannelWhereInput[]
  id?: Prisma.StringFilter<"NotificationChannel"> | string
  createdAt?: Prisma.DateTimeFilter<"NotificationChannel"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NotificationChannel"> | Date | string
  name?: Prisma.StringFilter<"NotificationChannel"> | string
  webhookUrl?: Prisma.StringFilter<"NotificationChannel"> | string
  headers?: Prisma.JsonNullableFilter<"NotificationChannel">
  bodyTemplate?: Prisma.StringFilter<"NotificationChannel"> | string
  enabled?: Prisma.BoolFilter<"NotificationChannel"> | boolean
}

export type NotificationChannelOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  webhookUrl?: Prisma.SortOrder
  headers?: Prisma.SortOrderInput | Prisma.SortOrder
  bodyTemplate?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
}

export type NotificationChannelWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.NotificationChannelWhereInput | Prisma.NotificationChannelWhereInput[]
  OR?: Prisma.NotificationChannelWhereInput[]
  NOT?: Prisma.NotificationChannelWhereInput | Prisma.NotificationChannelWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"NotificationChannel"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NotificationChannel"> | Date | string
  name?: Prisma.StringFilter<"NotificationChannel"> | string
  webhookUrl?: Prisma.StringFilter<"NotificationChannel"> | string
  headers?: Prisma.JsonNullableFilter<"NotificationChannel">
  bodyTemplate?: Prisma.StringFilter<"NotificationChannel"> | string
  enabled?: Prisma.BoolFilter<"NotificationChannel"> | boolean
}, "id">

export type NotificationChannelOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  webhookUrl?: Prisma.SortOrder
  headers?: Prisma.SortOrderInput | Prisma.SortOrder
  bodyTemplate?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  _count?: Prisma.NotificationChannelCountOrderByAggregateInput
  _max?: Prisma.NotificationChannelMaxOrderByAggregateInput
  _min?: Prisma.NotificationChannelMinOrderByAggregateInput
}

export type NotificationChannelScalarWhereWithAggregatesInput = {
  AND?: Prisma.NotificationChannelScalarWhereWithAggregatesInput | Prisma.NotificationChannelScalarWhereWithAggregatesInput[]
  OR?: Prisma.NotificationChannelScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NotificationChannelScalarWhereWithAggregatesInput | Prisma.NotificationChannelScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"NotificationChannel"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"NotificationChannel"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"NotificationChannel"> | Date | string
  name?: Prisma.StringWithAggregatesFilter<"NotificationChannel"> | string
  webhookUrl?: Prisma.StringWithAggregatesFilter<"NotificationChannel"> | string
  headers?: Prisma.JsonNullableWithAggregatesFilter<"NotificationChannel">
  bodyTemplate?: Prisma.StringWithAggregatesFilter<"NotificationChannel"> | string
  enabled?: Prisma.BoolWithAggregatesFilter<"NotificationChannel"> | boolean
}

export type NotificationChannelCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  webhookUrl: string
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  bodyTemplate: string
  enabled?: boolean
}

export type NotificationChannelUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  webhookUrl: string
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  bodyTemplate: string
  enabled?: boolean
}

export type NotificationChannelUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  webhookUrl?: Prisma.StringFieldUpdateOperationsInput | string
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  bodyTemplate?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type NotificationChannelUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  webhookUrl?: Prisma.StringFieldUpdateOperationsInput | string
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  bodyTemplate?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type NotificationChannelCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  webhookUrl: string
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  bodyTemplate: string
  enabled?: boolean
}

export type NotificationChannelUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  webhookUrl?: Prisma.StringFieldUpdateOperationsInput | string
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  bodyTemplate?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type NotificationChannelUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  webhookUrl?: Prisma.StringFieldUpdateOperationsInput | string
  headers?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  bodyTemplate?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type NotificationChannelCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  webhookUrl?: Prisma.SortOrder
  headers?: Prisma.SortOrder
  bodyTemplate?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
}

export type NotificationChannelMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  webhookUrl?: Prisma.SortOrder
  bodyTemplate?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
}

export type NotificationChannelMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  webhookUrl?: Prisma.SortOrder
  bodyTemplate?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
}



export type NotificationChannelSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  webhookUrl?: boolean
  headers?: boolean
  bodyTemplate?: boolean
  enabled?: boolean
}, ExtArgs["result"]["notificationChannel"]>

export type NotificationChannelSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  webhookUrl?: boolean
  headers?: boolean
  bodyTemplate?: boolean
  enabled?: boolean
}, ExtArgs["result"]["notificationChannel"]>

export type NotificationChannelSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  webhookUrl?: boolean
  headers?: boolean
  bodyTemplate?: boolean
  enabled?: boolean
}, ExtArgs["result"]["notificationChannel"]>

export type NotificationChannelSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  webhookUrl?: boolean
  headers?: boolean
  bodyTemplate?: boolean
  enabled?: boolean
}

export type NotificationChannelOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "name" | "webhookUrl" | "headers" | "bodyTemplate" | "enabled", ExtArgs["result"]["notificationChannel"]>

export type $NotificationChannelPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NotificationChannel"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    name: string
    webhookUrl: string
    headers: runtime.JsonValue | null
    bodyTemplate: string
    enabled: boolean
  }, ExtArgs["result"]["notificationChannel"]>
  composites: {}
}

export type NotificationChannelGetPayload<S extends boolean | null | undefined | NotificationChannelDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NotificationChannelPayload, S>

export type NotificationChannelCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NotificationChannelFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NotificationChannelCountAggregateInputType | true
  }

export interface NotificationChannelDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NotificationChannel'], meta: { name: 'NotificationChannel' } }
  /**
   * Find zero or one NotificationChannel that matches the filter.
   * @param {NotificationChannelFindUniqueArgs} args - Arguments to find a NotificationChannel
   * @example
   * // Get one NotificationChannel
   * const notificationChannel = await prisma.notificationChannel.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NotificationChannelFindUniqueArgs>(args: Prisma.SelectSubset<T, NotificationChannelFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NotificationChannelClient<runtime.Types.Result.GetResult<Prisma.$NotificationChannelPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NotificationChannel that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NotificationChannelFindUniqueOrThrowArgs} args - Arguments to find a NotificationChannel
   * @example
   * // Get one NotificationChannel
   * const notificationChannel = await prisma.notificationChannel.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NotificationChannelFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NotificationChannelFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NotificationChannelClient<runtime.Types.Result.GetResult<Prisma.$NotificationChannelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NotificationChannel that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationChannelFindFirstArgs} args - Arguments to find a NotificationChannel
   * @example
   * // Get one NotificationChannel
   * const notificationChannel = await prisma.notificationChannel.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NotificationChannelFindFirstArgs>(args?: Prisma.SelectSubset<T, NotificationChannelFindFirstArgs<ExtArgs>>): Prisma.Prisma__NotificationChannelClient<runtime.Types.Result.GetResult<Prisma.$NotificationChannelPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NotificationChannel that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationChannelFindFirstOrThrowArgs} args - Arguments to find a NotificationChannel
   * @example
   * // Get one NotificationChannel
   * const notificationChannel = await prisma.notificationChannel.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NotificationChannelFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NotificationChannelFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NotificationChannelClient<runtime.Types.Result.GetResult<Prisma.$NotificationChannelPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NotificationChannels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationChannelFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NotificationChannels
   * const notificationChannels = await prisma.notificationChannel.findMany()
   * 
   * // Get first 10 NotificationChannels
   * const notificationChannels = await prisma.notificationChannel.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const notificationChannelWithIdOnly = await prisma.notificationChannel.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NotificationChannelFindManyArgs>(args?: Prisma.SelectSubset<T, NotificationChannelFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationChannelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NotificationChannel.
   * @param {NotificationChannelCreateArgs} args - Arguments to create a NotificationChannel.
   * @example
   * // Create one NotificationChannel
   * const NotificationChannel = await prisma.notificationChannel.create({
   *   data: {
   *     // ... data to create a NotificationChannel
   *   }
   * })
   * 
   */
  create<T extends NotificationChannelCreateArgs>(args: Prisma.SelectSubset<T, NotificationChannelCreateArgs<ExtArgs>>): Prisma.Prisma__NotificationChannelClient<runtime.Types.Result.GetResult<Prisma.$NotificationChannelPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NotificationChannels.
   * @param {NotificationChannelCreateManyArgs} args - Arguments to create many NotificationChannels.
   * @example
   * // Create many NotificationChannels
   * const notificationChannel = await prisma.notificationChannel.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NotificationChannelCreateManyArgs>(args?: Prisma.SelectSubset<T, NotificationChannelCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many NotificationChannels and returns the data saved in the database.
   * @param {NotificationChannelCreateManyAndReturnArgs} args - Arguments to create many NotificationChannels.
   * @example
   * // Create many NotificationChannels
   * const notificationChannel = await prisma.notificationChannel.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many NotificationChannels and only return the `id`
   * const notificationChannelWithIdOnly = await prisma.notificationChannel.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NotificationChannelCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NotificationChannelCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationChannelPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a NotificationChannel.
   * @param {NotificationChannelDeleteArgs} args - Arguments to delete one NotificationChannel.
   * @example
   * // Delete one NotificationChannel
   * const NotificationChannel = await prisma.notificationChannel.delete({
   *   where: {
   *     // ... filter to delete one NotificationChannel
   *   }
   * })
   * 
   */
  delete<T extends NotificationChannelDeleteArgs>(args: Prisma.SelectSubset<T, NotificationChannelDeleteArgs<ExtArgs>>): Prisma.Prisma__NotificationChannelClient<runtime.Types.Result.GetResult<Prisma.$NotificationChannelPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NotificationChannel.
   * @param {NotificationChannelUpdateArgs} args - Arguments to update one NotificationChannel.
   * @example
   * // Update one NotificationChannel
   * const notificationChannel = await prisma.notificationChannel.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NotificationChannelUpdateArgs>(args: Prisma.SelectSubset<T, NotificationChannelUpdateArgs<ExtArgs>>): Prisma.Prisma__NotificationChannelClient<runtime.Types.Result.GetResult<Prisma.$NotificationChannelPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NotificationChannels.
   * @param {NotificationChannelDeleteManyArgs} args - Arguments to filter NotificationChannels to delete.
   * @example
   * // Delete a few NotificationChannels
   * const { count } = await prisma.notificationChannel.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NotificationChannelDeleteManyArgs>(args?: Prisma.SelectSubset<T, NotificationChannelDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NotificationChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationChannelUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NotificationChannels
   * const notificationChannel = await prisma.notificationChannel.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NotificationChannelUpdateManyArgs>(args: Prisma.SelectSubset<T, NotificationChannelUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NotificationChannels and returns the data updated in the database.
   * @param {NotificationChannelUpdateManyAndReturnArgs} args - Arguments to update many NotificationChannels.
   * @example
   * // Update many NotificationChannels
   * const notificationChannel = await prisma.notificationChannel.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more NotificationChannels and only return the `id`
   * const notificationChannelWithIdOnly = await prisma.notificationChannel.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NotificationChannelUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NotificationChannelUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotificationChannelPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one NotificationChannel.
   * @param {NotificationChannelUpsertArgs} args - Arguments to update or create a NotificationChannel.
   * @example
   * // Update or create a NotificationChannel
   * const notificationChannel = await prisma.notificationChannel.upsert({
   *   create: {
   *     // ... data to create a NotificationChannel
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NotificationChannel we want to update
   *   }
   * })
   */
  upsert<T extends NotificationChannelUpsertArgs>(args: Prisma.SelectSubset<T, NotificationChannelUpsertArgs<ExtArgs>>): Prisma.Prisma__NotificationChannelClient<runtime.Types.Result.GetResult<Prisma.$NotificationChannelPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NotificationChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationChannelCountArgs} args - Arguments to filter NotificationChannels to count.
   * @example
   * // Count the number of NotificationChannels
   * const count = await prisma.notificationChannel.count({
   *   where: {
   *     // ... the filter for the NotificationChannels we want to count
   *   }
   * })
  **/
  count<T extends NotificationChannelCountArgs>(
    args?: Prisma.Subset<T, NotificationChannelCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NotificationChannelCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NotificationChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationChannelAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NotificationChannelAggregateArgs>(args: Prisma.Subset<T, NotificationChannelAggregateArgs>): Prisma.PrismaPromise<GetNotificationChannelAggregateType<T>>

  /**
   * Group by NotificationChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotificationChannelGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NotificationChannelGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NotificationChannelGroupByArgs['orderBy'] }
      : { orderBy?: NotificationChannelGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NotificationChannelGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNotificationChannelGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NotificationChannel model
 */
readonly fields: NotificationChannelFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NotificationChannel.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NotificationChannelClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NotificationChannel model
 */
export interface NotificationChannelFieldRefs {
  readonly id: Prisma.FieldRef<"NotificationChannel", 'String'>
  readonly createdAt: Prisma.FieldRef<"NotificationChannel", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"NotificationChannel", 'DateTime'>
  readonly name: Prisma.FieldRef<"NotificationChannel", 'String'>
  readonly webhookUrl: Prisma.FieldRef<"NotificationChannel", 'String'>
  readonly headers: Prisma.FieldRef<"NotificationChannel", 'Json'>
  readonly bodyTemplate: Prisma.FieldRef<"NotificationChannel", 'String'>
  readonly enabled: Prisma.FieldRef<"NotificationChannel", 'Boolean'>
}
    

// Custom InputTypes
/**
 * NotificationChannel findUnique
 */
export type NotificationChannelFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationChannel
   */
  select?: Prisma.NotificationChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationChannel
   */
  omit?: Prisma.NotificationChannelOmit<ExtArgs> | null
  /**
   * Filter, which NotificationChannel to fetch.
   */
  where: Prisma.NotificationChannelWhereUniqueInput
}

/**
 * NotificationChannel findUniqueOrThrow
 */
export type NotificationChannelFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationChannel
   */
  select?: Prisma.NotificationChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationChannel
   */
  omit?: Prisma.NotificationChannelOmit<ExtArgs> | null
  /**
   * Filter, which NotificationChannel to fetch.
   */
  where: Prisma.NotificationChannelWhereUniqueInput
}

/**
 * NotificationChannel findFirst
 */
export type NotificationChannelFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationChannel
   */
  select?: Prisma.NotificationChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationChannel
   */
  omit?: Prisma.NotificationChannelOmit<ExtArgs> | null
  /**
   * Filter, which NotificationChannel to fetch.
   */
  where?: Prisma.NotificationChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NotificationChannels to fetch.
   */
  orderBy?: Prisma.NotificationChannelOrderByWithRelationInput | Prisma.NotificationChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NotificationChannels.
   */
  cursor?: Prisma.NotificationChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NotificationChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NotificationChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NotificationChannels.
   */
  distinct?: Prisma.NotificationChannelScalarFieldEnum | Prisma.NotificationChannelScalarFieldEnum[]
}

/**
 * NotificationChannel findFirstOrThrow
 */
export type NotificationChannelFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationChannel
   */
  select?: Prisma.NotificationChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationChannel
   */
  omit?: Prisma.NotificationChannelOmit<ExtArgs> | null
  /**
   * Filter, which NotificationChannel to fetch.
   */
  where?: Prisma.NotificationChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NotificationChannels to fetch.
   */
  orderBy?: Prisma.NotificationChannelOrderByWithRelationInput | Prisma.NotificationChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NotificationChannels.
   */
  cursor?: Prisma.NotificationChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NotificationChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NotificationChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NotificationChannels.
   */
  distinct?: Prisma.NotificationChannelScalarFieldEnum | Prisma.NotificationChannelScalarFieldEnum[]
}

/**
 * NotificationChannel findMany
 */
export type NotificationChannelFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationChannel
   */
  select?: Prisma.NotificationChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationChannel
   */
  omit?: Prisma.NotificationChannelOmit<ExtArgs> | null
  /**
   * Filter, which NotificationChannels to fetch.
   */
  where?: Prisma.NotificationChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NotificationChannels to fetch.
   */
  orderBy?: Prisma.NotificationChannelOrderByWithRelationInput | Prisma.NotificationChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NotificationChannels.
   */
  cursor?: Prisma.NotificationChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NotificationChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NotificationChannels.
   */
  skip?: number
  distinct?: Prisma.NotificationChannelScalarFieldEnum | Prisma.NotificationChannelScalarFieldEnum[]
}

/**
 * NotificationChannel create
 */
export type NotificationChannelCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationChannel
   */
  select?: Prisma.NotificationChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationChannel
   */
  omit?: Prisma.NotificationChannelOmit<ExtArgs> | null
  /**
   * The data needed to create a NotificationChannel.
   */
  data: Prisma.XOR<Prisma.NotificationChannelCreateInput, Prisma.NotificationChannelUncheckedCreateInput>
}

/**
 * NotificationChannel createMany
 */
export type NotificationChannelCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NotificationChannels.
   */
  data: Prisma.NotificationChannelCreateManyInput | Prisma.NotificationChannelCreateManyInput[]
}

/**
 * NotificationChannel createManyAndReturn
 */
export type NotificationChannelCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationChannel
   */
  select?: Prisma.NotificationChannelSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationChannel
   */
  omit?: Prisma.NotificationChannelOmit<ExtArgs> | null
  /**
   * The data used to create many NotificationChannels.
   */
  data: Prisma.NotificationChannelCreateManyInput | Prisma.NotificationChannelCreateManyInput[]
}

/**
 * NotificationChannel update
 */
export type NotificationChannelUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationChannel
   */
  select?: Prisma.NotificationChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationChannel
   */
  omit?: Prisma.NotificationChannelOmit<ExtArgs> | null
  /**
   * The data needed to update a NotificationChannel.
   */
  data: Prisma.XOR<Prisma.NotificationChannelUpdateInput, Prisma.NotificationChannelUncheckedUpdateInput>
  /**
   * Choose, which NotificationChannel to update.
   */
  where: Prisma.NotificationChannelWhereUniqueInput
}

/**
 * NotificationChannel updateMany
 */
export type NotificationChannelUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NotificationChannels.
   */
  data: Prisma.XOR<Prisma.NotificationChannelUpdateManyMutationInput, Prisma.NotificationChannelUncheckedUpdateManyInput>
  /**
   * Filter which NotificationChannels to update
   */
  where?: Prisma.NotificationChannelWhereInput
  /**
   * Limit how many NotificationChannels to update.
   */
  limit?: number
}

/**
 * NotificationChannel updateManyAndReturn
 */
export type NotificationChannelUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationChannel
   */
  select?: Prisma.NotificationChannelSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationChannel
   */
  omit?: Prisma.NotificationChannelOmit<ExtArgs> | null
  /**
   * The data used to update NotificationChannels.
   */
  data: Prisma.XOR<Prisma.NotificationChannelUpdateManyMutationInput, Prisma.NotificationChannelUncheckedUpdateManyInput>
  /**
   * Filter which NotificationChannels to update
   */
  where?: Prisma.NotificationChannelWhereInput
  /**
   * Limit how many NotificationChannels to update.
   */
  limit?: number
}

/**
 * NotificationChannel upsert
 */
export type NotificationChannelUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationChannel
   */
  select?: Prisma.NotificationChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationChannel
   */
  omit?: Prisma.NotificationChannelOmit<ExtArgs> | null
  /**
   * The filter to search for the NotificationChannel to update in case it exists.
   */
  where: Prisma.NotificationChannelWhereUniqueInput
  /**
   * In case the NotificationChannel found by the `where` argument doesn't exist, create a new NotificationChannel with this data.
   */
  create: Prisma.XOR<Prisma.NotificationChannelCreateInput, Prisma.NotificationChannelUncheckedCreateInput>
  /**
   * In case the NotificationChannel was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NotificationChannelUpdateInput, Prisma.NotificationChannelUncheckedUpdateInput>
}

/**
 * NotificationChannel delete
 */
export type NotificationChannelDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationChannel
   */
  select?: Prisma.NotificationChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationChannel
   */
  omit?: Prisma.NotificationChannelOmit<ExtArgs> | null
  /**
   * Filter which NotificationChannel to delete.
   */
  where: Prisma.NotificationChannelWhereUniqueInput
}

/**
 * NotificationChannel deleteMany
 */
export type NotificationChannelDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NotificationChannels to delete
   */
  where?: Prisma.NotificationChannelWhereInput
  /**
   * Limit how many NotificationChannels to delete.
   */
  limit?: number
}

/**
 * NotificationChannel without action
 */
export type NotificationChannelDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NotificationChannel
   */
  select?: Prisma.NotificationChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NotificationChannel
   */
  omit?: Prisma.NotificationChannelOmit<ExtArgs> | null
}
