
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProbeHourlyStat` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProbeHourlyStat
 * 
 */
export type ProbeHourlyStatModel = runtime.Types.Result.DefaultSelection<Prisma.$ProbeHourlyStatPayload>

export type AggregateProbeHourlyStat = {
  _count: ProbeHourlyStatCountAggregateOutputType | null
  _avg: ProbeHourlyStatAvgAggregateOutputType | null
  _sum: ProbeHourlyStatSumAggregateOutputType | null
  _min: ProbeHourlyStatMinAggregateOutputType | null
  _max: ProbeHourlyStatMaxAggregateOutputType | null
}

export type ProbeHourlyStatAvgAggregateOutputType = {
  totalChecks: number | null
  successCount: number | null
  avgResponseTime: number | null
  minResponseTime: number | null
  maxResponseTime: number | null
}

export type ProbeHourlyStatSumAggregateOutputType = {
  totalChecks: number | null
  successCount: number | null
  avgResponseTime: number | null
  minResponseTime: number | null
  maxResponseTime: number | null
}

export type ProbeHourlyStatMinAggregateOutputType = {
  endPointId: string | null
  hourTimestamp: Date | null
  totalChecks: number | null
  successCount: number | null
  avgResponseTime: number | null
  minResponseTime: number | null
  maxResponseTime: number | null
}

export type ProbeHourlyStatMaxAggregateOutputType = {
  endPointId: string | null
  hourTimestamp: Date | null
  totalChecks: number | null
  successCount: number | null
  avgResponseTime: number | null
  minResponseTime: number | null
  maxResponseTime: number | null
}

export type ProbeHourlyStatCountAggregateOutputType = {
  endPointId: number
  hourTimestamp: number
  totalChecks: number
  successCount: number
  avgResponseTime: number
  minResponseTime: number
  maxResponseTime: number
  _all: number
}


export type ProbeHourlyStatAvgAggregateInputType = {
  totalChecks?: true
  successCount?: true
  avgResponseTime?: true
  minResponseTime?: true
  maxResponseTime?: true
}

export type ProbeHourlyStatSumAggregateInputType = {
  totalChecks?: true
  successCount?: true
  avgResponseTime?: true
  minResponseTime?: true
  maxResponseTime?: true
}

export type ProbeHourlyStatMinAggregateInputType = {
  endPointId?: true
  hourTimestamp?: true
  totalChecks?: true
  successCount?: true
  avgResponseTime?: true
  minResponseTime?: true
  maxResponseTime?: true
}

export type ProbeHourlyStatMaxAggregateInputType = {
  endPointId?: true
  hourTimestamp?: true
  totalChecks?: true
  successCount?: true
  avgResponseTime?: true
  minResponseTime?: true
  maxResponseTime?: true
}

export type ProbeHourlyStatCountAggregateInputType = {
  endPointId?: true
  hourTimestamp?: true
  totalChecks?: true
  successCount?: true
  avgResponseTime?: true
  minResponseTime?: true
  maxResponseTime?: true
  _all?: true
}

export type ProbeHourlyStatAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProbeHourlyStat to aggregate.
   */
  where?: Prisma.ProbeHourlyStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProbeHourlyStats to fetch.
   */
  orderBy?: Prisma.ProbeHourlyStatOrderByWithRelationInput | Prisma.ProbeHourlyStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProbeHourlyStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProbeHourlyStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProbeHourlyStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProbeHourlyStats
  **/
  _count?: true | ProbeHourlyStatCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProbeHourlyStatAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProbeHourlyStatSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProbeHourlyStatMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProbeHourlyStatMaxAggregateInputType
}

export type GetProbeHourlyStatAggregateType<T extends ProbeHourlyStatAggregateArgs> = {
      [P in keyof T & keyof AggregateProbeHourlyStat]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProbeHourlyStat[P]>
    : Prisma.GetScalarType<T[P], AggregateProbeHourlyStat[P]>
}




export type ProbeHourlyStatGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProbeHourlyStatWhereInput
  orderBy?: Prisma.ProbeHourlyStatOrderByWithAggregationInput | Prisma.ProbeHourlyStatOrderByWithAggregationInput[]
  by: Prisma.ProbeHourlyStatScalarFieldEnum[] | Prisma.ProbeHourlyStatScalarFieldEnum
  having?: Prisma.ProbeHourlyStatScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProbeHourlyStatCountAggregateInputType | true
  _avg?: ProbeHourlyStatAvgAggregateInputType
  _sum?: ProbeHourlyStatSumAggregateInputType
  _min?: ProbeHourlyStatMinAggregateInputType
  _max?: ProbeHourlyStatMaxAggregateInputType
}

export type ProbeHourlyStatGroupByOutputType = {
  endPointId: string
  hourTimestamp: Date
  totalChecks: number
  successCount: number
  avgResponseTime: number | null
  minResponseTime: number | null
  maxResponseTime: number | null
  _count: ProbeHourlyStatCountAggregateOutputType | null
  _avg: ProbeHourlyStatAvgAggregateOutputType | null
  _sum: ProbeHourlyStatSumAggregateOutputType | null
  _min: ProbeHourlyStatMinAggregateOutputType | null
  _max: ProbeHourlyStatMaxAggregateOutputType | null
}

type GetProbeHourlyStatGroupByPayload<T extends ProbeHourlyStatGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProbeHourlyStatGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProbeHourlyStatGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProbeHourlyStatGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProbeHourlyStatGroupByOutputType[P]>
      }
    >
  >



export type ProbeHourlyStatWhereInput = {
  AND?: Prisma.ProbeHourlyStatWhereInput | Prisma.ProbeHourlyStatWhereInput[]
  OR?: Prisma.ProbeHourlyStatWhereInput[]
  NOT?: Prisma.ProbeHourlyStatWhereInput | Prisma.ProbeHourlyStatWhereInput[]
  endPointId?: Prisma.StringFilter<"ProbeHourlyStat"> | string
  hourTimestamp?: Prisma.DateTimeFilter<"ProbeHourlyStat"> | Date | string
  totalChecks?: Prisma.IntFilter<"ProbeHourlyStat"> | number
  successCount?: Prisma.IntFilter<"ProbeHourlyStat"> | number
  avgResponseTime?: Prisma.IntNullableFilter<"ProbeHourlyStat"> | number | null
  minResponseTime?: Prisma.IntNullableFilter<"ProbeHourlyStat"> | number | null
  maxResponseTime?: Prisma.IntNullableFilter<"ProbeHourlyStat"> | number | null
  endPoint?: Prisma.XOR<Prisma.EndPointScalarRelationFilter, Prisma.EndPointWhereInput>
}

export type ProbeHourlyStatOrderByWithRelationInput = {
  endPointId?: Prisma.SortOrder
  hourTimestamp?: Prisma.SortOrder
  totalChecks?: Prisma.SortOrder
  successCount?: Prisma.SortOrder
  avgResponseTime?: Prisma.SortOrderInput | Prisma.SortOrder
  minResponseTime?: Prisma.SortOrderInput | Prisma.SortOrder
  maxResponseTime?: Prisma.SortOrderInput | Prisma.SortOrder
  endPoint?: Prisma.EndPointOrderByWithRelationInput
}

export type ProbeHourlyStatWhereUniqueInput = Prisma.AtLeast<{
  endPointId_hourTimestamp?: Prisma.ProbeHourlyStatEndPointIdHourTimestampCompoundUniqueInput
  AND?: Prisma.ProbeHourlyStatWhereInput | Prisma.ProbeHourlyStatWhereInput[]
  OR?: Prisma.ProbeHourlyStatWhereInput[]
  NOT?: Prisma.ProbeHourlyStatWhereInput | Prisma.ProbeHourlyStatWhereInput[]
  endPointId?: Prisma.StringFilter<"ProbeHourlyStat"> | string
  hourTimestamp?: Prisma.DateTimeFilter<"ProbeHourlyStat"> | Date | string
  totalChecks?: Prisma.IntFilter<"ProbeHourlyStat"> | number
  successCount?: Prisma.IntFilter<"ProbeHourlyStat"> | number
  avgResponseTime?: Prisma.IntNullableFilter<"ProbeHourlyStat"> | number | null
  minResponseTime?: Prisma.IntNullableFilter<"ProbeHourlyStat"> | number | null
  maxResponseTime?: Prisma.IntNullableFilter<"ProbeHourlyStat"> | number | null
  endPoint?: Prisma.XOR<Prisma.EndPointScalarRelationFilter, Prisma.EndPointWhereInput>
}, "endPointId_hourTimestamp">

export type ProbeHourlyStatOrderByWithAggregationInput = {
  endPointId?: Prisma.SortOrder
  hourTimestamp?: Prisma.SortOrder
  totalChecks?: Prisma.SortOrder
  successCount?: Prisma.SortOrder
  avgResponseTime?: Prisma.SortOrderInput | Prisma.SortOrder
  minResponseTime?: Prisma.SortOrderInput | Prisma.SortOrder
  maxResponseTime?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ProbeHourlyStatCountOrderByAggregateInput
  _avg?: Prisma.ProbeHourlyStatAvgOrderByAggregateInput
  _max?: Prisma.ProbeHourlyStatMaxOrderByAggregateInput
  _min?: Prisma.ProbeHourlyStatMinOrderByAggregateInput
  _sum?: Prisma.ProbeHourlyStatSumOrderByAggregateInput
}

export type ProbeHourlyStatScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProbeHourlyStatScalarWhereWithAggregatesInput | Prisma.ProbeHourlyStatScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProbeHourlyStatScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProbeHourlyStatScalarWhereWithAggregatesInput | Prisma.ProbeHourlyStatScalarWhereWithAggregatesInput[]
  endPointId?: Prisma.StringWithAggregatesFilter<"ProbeHourlyStat"> | string
  hourTimestamp?: Prisma.DateTimeWithAggregatesFilter<"ProbeHourlyStat"> | Date | string
  totalChecks?: Prisma.IntWithAggregatesFilter<"ProbeHourlyStat"> | number
  successCount?: Prisma.IntWithAggregatesFilter<"ProbeHourlyStat"> | number
  avgResponseTime?: Prisma.IntNullableWithAggregatesFilter<"ProbeHourlyStat"> | number | null
  minResponseTime?: Prisma.IntNullableWithAggregatesFilter<"ProbeHourlyStat"> | number | null
  maxResponseTime?: Prisma.IntNullableWithAggregatesFilter<"ProbeHourlyStat"> | number | null
}

export type ProbeHourlyStatCreateInput = {
  hourTimestamp: Date | string
  totalChecks: number
  successCount: number
  avgResponseTime?: number | null
  minResponseTime?: number | null
  maxResponseTime?: number | null
  endPoint: Prisma.EndPointCreateNestedOneWithoutHourlyStatsInput
}

export type ProbeHourlyStatUncheckedCreateInput = {
  endPointId: string
  hourTimestamp: Date | string
  totalChecks: number
  successCount: number
  avgResponseTime?: number | null
  minResponseTime?: number | null
  maxResponseTime?: number | null
}

export type ProbeHourlyStatUpdateInput = {
  hourTimestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalChecks?: Prisma.IntFieldUpdateOperationsInput | number
  successCount?: Prisma.IntFieldUpdateOperationsInput | number
  avgResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  minResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endPoint?: Prisma.EndPointUpdateOneRequiredWithoutHourlyStatsNestedInput
}

export type ProbeHourlyStatUncheckedUpdateInput = {
  endPointId?: Prisma.StringFieldUpdateOperationsInput | string
  hourTimestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalChecks?: Prisma.IntFieldUpdateOperationsInput | number
  successCount?: Prisma.IntFieldUpdateOperationsInput | number
  avgResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  minResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ProbeHourlyStatCreateManyInput = {
  endPointId: string
  hourTimestamp: Date | string
  totalChecks: number
  successCount: number
  avgResponseTime?: number | null
  minResponseTime?: number | null
  maxResponseTime?: number | null
}

export type ProbeHourlyStatUpdateManyMutationInput = {
  hourTimestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalChecks?: Prisma.IntFieldUpdateOperationsInput | number
  successCount?: Prisma.IntFieldUpdateOperationsInput | number
  avgResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  minResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ProbeHourlyStatUncheckedUpdateManyInput = {
  endPointId?: Prisma.StringFieldUpdateOperationsInput | string
  hourTimestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalChecks?: Prisma.IntFieldUpdateOperationsInput | number
  successCount?: Prisma.IntFieldUpdateOperationsInput | number
  avgResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  minResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ProbeHourlyStatListRelationFilter = {
  every?: Prisma.ProbeHourlyStatWhereInput
  some?: Prisma.ProbeHourlyStatWhereInput
  none?: Prisma.ProbeHourlyStatWhereInput
}

export type ProbeHourlyStatOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProbeHourlyStatEndPointIdHourTimestampCompoundUniqueInput = {
  endPointId: string
  hourTimestamp: Date | string
}

export type ProbeHourlyStatCountOrderByAggregateInput = {
  endPointId?: Prisma.SortOrder
  hourTimestamp?: Prisma.SortOrder
  totalChecks?: Prisma.SortOrder
  successCount?: Prisma.SortOrder
  avgResponseTime?: Prisma.SortOrder
  minResponseTime?: Prisma.SortOrder
  maxResponseTime?: Prisma.SortOrder
}

export type ProbeHourlyStatAvgOrderByAggregateInput = {
  totalChecks?: Prisma.SortOrder
  successCount?: Prisma.SortOrder
  avgResponseTime?: Prisma.SortOrder
  minResponseTime?: Prisma.SortOrder
  maxResponseTime?: Prisma.SortOrder
}

export type ProbeHourlyStatMaxOrderByAggregateInput = {
  endPointId?: Prisma.SortOrder
  hourTimestamp?: Prisma.SortOrder
  totalChecks?: Prisma.SortOrder
  successCount?: Prisma.SortOrder
  avgResponseTime?: Prisma.SortOrder
  minResponseTime?: Prisma.SortOrder
  maxResponseTime?: Prisma.SortOrder
}

export type ProbeHourlyStatMinOrderByAggregateInput = {
  endPointId?: Prisma.SortOrder
  hourTimestamp?: Prisma.SortOrder
  totalChecks?: Prisma.SortOrder
  successCount?: Prisma.SortOrder
  avgResponseTime?: Prisma.SortOrder
  minResponseTime?: Prisma.SortOrder
  maxResponseTime?: Prisma.SortOrder
}

export type ProbeHourlyStatSumOrderByAggregateInput = {
  totalChecks?: Prisma.SortOrder
  successCount?: Prisma.SortOrder
  avgResponseTime?: Prisma.SortOrder
  minResponseTime?: Prisma.SortOrder
  maxResponseTime?: Prisma.SortOrder
}

export type ProbeHourlyStatCreateNestedManyWithoutEndPointInput = {
  create?: Prisma.XOR<Prisma.ProbeHourlyStatCreateWithoutEndPointInput, Prisma.ProbeHourlyStatUncheckedCreateWithoutEndPointInput> | Prisma.ProbeHourlyStatCreateWithoutEndPointInput[] | Prisma.ProbeHourlyStatUncheckedCreateWithoutEndPointInput[]
  connectOrCreate?: Prisma.ProbeHourlyStatCreateOrConnectWithoutEndPointInput | Prisma.ProbeHourlyStatCreateOrConnectWithoutEndPointInput[]
  createMany?: Prisma.ProbeHourlyStatCreateManyEndPointInputEnvelope
  connect?: Prisma.ProbeHourlyStatWhereUniqueInput | Prisma.ProbeHourlyStatWhereUniqueInput[]
}

export type ProbeHourlyStatUncheckedCreateNestedManyWithoutEndPointInput = {
  create?: Prisma.XOR<Prisma.ProbeHourlyStatCreateWithoutEndPointInput, Prisma.ProbeHourlyStatUncheckedCreateWithoutEndPointInput> | Prisma.ProbeHourlyStatCreateWithoutEndPointInput[] | Prisma.ProbeHourlyStatUncheckedCreateWithoutEndPointInput[]
  connectOrCreate?: Prisma.ProbeHourlyStatCreateOrConnectWithoutEndPointInput | Prisma.ProbeHourlyStatCreateOrConnectWithoutEndPointInput[]
  createMany?: Prisma.ProbeHourlyStatCreateManyEndPointInputEnvelope
  connect?: Prisma.ProbeHourlyStatWhereUniqueInput | Prisma.ProbeHourlyStatWhereUniqueInput[]
}

export type ProbeHourlyStatUpdateManyWithoutEndPointNestedInput = {
  create?: Prisma.XOR<Prisma.ProbeHourlyStatCreateWithoutEndPointInput, Prisma.ProbeHourlyStatUncheckedCreateWithoutEndPointInput> | Prisma.ProbeHourlyStatCreateWithoutEndPointInput[] | Prisma.ProbeHourlyStatUncheckedCreateWithoutEndPointInput[]
  connectOrCreate?: Prisma.ProbeHourlyStatCreateOrConnectWithoutEndPointInput | Prisma.ProbeHourlyStatCreateOrConnectWithoutEndPointInput[]
  upsert?: Prisma.ProbeHourlyStatUpsertWithWhereUniqueWithoutEndPointInput | Prisma.ProbeHourlyStatUpsertWithWhereUniqueWithoutEndPointInput[]
  createMany?: Prisma.ProbeHourlyStatCreateManyEndPointInputEnvelope
  set?: Prisma.ProbeHourlyStatWhereUniqueInput | Prisma.ProbeHourlyStatWhereUniqueInput[]
  disconnect?: Prisma.ProbeHourlyStatWhereUniqueInput | Prisma.ProbeHourlyStatWhereUniqueInput[]
  delete?: Prisma.ProbeHourlyStatWhereUniqueInput | Prisma.ProbeHourlyStatWhereUniqueInput[]
  connect?: Prisma.ProbeHourlyStatWhereUniqueInput | Prisma.ProbeHourlyStatWhereUniqueInput[]
  update?: Prisma.ProbeHourlyStatUpdateWithWhereUniqueWithoutEndPointInput | Prisma.ProbeHourlyStatUpdateWithWhereUniqueWithoutEndPointInput[]
  updateMany?: Prisma.ProbeHourlyStatUpdateManyWithWhereWithoutEndPointInput | Prisma.ProbeHourlyStatUpdateManyWithWhereWithoutEndPointInput[]
  deleteMany?: Prisma.ProbeHourlyStatScalarWhereInput | Prisma.ProbeHourlyStatScalarWhereInput[]
}

export type ProbeHourlyStatUncheckedUpdateManyWithoutEndPointNestedInput = {
  create?: Prisma.XOR<Prisma.ProbeHourlyStatCreateWithoutEndPointInput, Prisma.ProbeHourlyStatUncheckedCreateWithoutEndPointInput> | Prisma.ProbeHourlyStatCreateWithoutEndPointInput[] | Prisma.ProbeHourlyStatUncheckedCreateWithoutEndPointInput[]
  connectOrCreate?: Prisma.ProbeHourlyStatCreateOrConnectWithoutEndPointInput | Prisma.ProbeHourlyStatCreateOrConnectWithoutEndPointInput[]
  upsert?: Prisma.ProbeHourlyStatUpsertWithWhereUniqueWithoutEndPointInput | Prisma.ProbeHourlyStatUpsertWithWhereUniqueWithoutEndPointInput[]
  createMany?: Prisma.ProbeHourlyStatCreateManyEndPointInputEnvelope
  set?: Prisma.ProbeHourlyStatWhereUniqueInput | Prisma.ProbeHourlyStatWhereUniqueInput[]
  disconnect?: Prisma.ProbeHourlyStatWhereUniqueInput | Prisma.ProbeHourlyStatWhereUniqueInput[]
  delete?: Prisma.ProbeHourlyStatWhereUniqueInput | Prisma.ProbeHourlyStatWhereUniqueInput[]
  connect?: Prisma.ProbeHourlyStatWhereUniqueInput | Prisma.ProbeHourlyStatWhereUniqueInput[]
  update?: Prisma.ProbeHourlyStatUpdateWithWhereUniqueWithoutEndPointInput | Prisma.ProbeHourlyStatUpdateWithWhereUniqueWithoutEndPointInput[]
  updateMany?: Prisma.ProbeHourlyStatUpdateManyWithWhereWithoutEndPointInput | Prisma.ProbeHourlyStatUpdateManyWithWhereWithoutEndPointInput[]
  deleteMany?: Prisma.ProbeHourlyStatScalarWhereInput | Prisma.ProbeHourlyStatScalarWhereInput[]
}

export type ProbeHourlyStatCreateWithoutEndPointInput = {
  hourTimestamp: Date | string
  totalChecks: number
  successCount: number
  avgResponseTime?: number | null
  minResponseTime?: number | null
  maxResponseTime?: number | null
}

export type ProbeHourlyStatUncheckedCreateWithoutEndPointInput = {
  hourTimestamp: Date | string
  totalChecks: number
  successCount: number
  avgResponseTime?: number | null
  minResponseTime?: number | null
  maxResponseTime?: number | null
}

export type ProbeHourlyStatCreateOrConnectWithoutEndPointInput = {
  where: Prisma.ProbeHourlyStatWhereUniqueInput
  create: Prisma.XOR<Prisma.ProbeHourlyStatCreateWithoutEndPointInput, Prisma.ProbeHourlyStatUncheckedCreateWithoutEndPointInput>
}

export type ProbeHourlyStatCreateManyEndPointInputEnvelope = {
  data: Prisma.ProbeHourlyStatCreateManyEndPointInput | Prisma.ProbeHourlyStatCreateManyEndPointInput[]
}

export type ProbeHourlyStatUpsertWithWhereUniqueWithoutEndPointInput = {
  where: Prisma.ProbeHourlyStatWhereUniqueInput
  update: Prisma.XOR<Prisma.ProbeHourlyStatUpdateWithoutEndPointInput, Prisma.ProbeHourlyStatUncheckedUpdateWithoutEndPointInput>
  create: Prisma.XOR<Prisma.ProbeHourlyStatCreateWithoutEndPointInput, Prisma.ProbeHourlyStatUncheckedCreateWithoutEndPointInput>
}

export type ProbeHourlyStatUpdateWithWhereUniqueWithoutEndPointInput = {
  where: Prisma.ProbeHourlyStatWhereUniqueInput
  data: Prisma.XOR<Prisma.ProbeHourlyStatUpdateWithoutEndPointInput, Prisma.ProbeHourlyStatUncheckedUpdateWithoutEndPointInput>
}

export type ProbeHourlyStatUpdateManyWithWhereWithoutEndPointInput = {
  where: Prisma.ProbeHourlyStatScalarWhereInput
  data: Prisma.XOR<Prisma.ProbeHourlyStatUpdateManyMutationInput, Prisma.ProbeHourlyStatUncheckedUpdateManyWithoutEndPointInput>
}

export type ProbeHourlyStatScalarWhereInput = {
  AND?: Prisma.ProbeHourlyStatScalarWhereInput | Prisma.ProbeHourlyStatScalarWhereInput[]
  OR?: Prisma.ProbeHourlyStatScalarWhereInput[]
  NOT?: Prisma.ProbeHourlyStatScalarWhereInput | Prisma.ProbeHourlyStatScalarWhereInput[]
  endPointId?: Prisma.StringFilter<"ProbeHourlyStat"> | string
  hourTimestamp?: Prisma.DateTimeFilter<"ProbeHourlyStat"> | Date | string
  totalChecks?: Prisma.IntFilter<"ProbeHourlyStat"> | number
  successCount?: Prisma.IntFilter<"ProbeHourlyStat"> | number
  avgResponseTime?: Prisma.IntNullableFilter<"ProbeHourlyStat"> | number | null
  minResponseTime?: Prisma.IntNullableFilter<"ProbeHourlyStat"> | number | null
  maxResponseTime?: Prisma.IntNullableFilter<"ProbeHourlyStat"> | number | null
}

export type ProbeHourlyStatCreateManyEndPointInput = {
  hourTimestamp: Date | string
  totalChecks: number
  successCount: number
  avgResponseTime?: number | null
  minResponseTime?: number | null
  maxResponseTime?: number | null
}

export type ProbeHourlyStatUpdateWithoutEndPointInput = {
  hourTimestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalChecks?: Prisma.IntFieldUpdateOperationsInput | number
  successCount?: Prisma.IntFieldUpdateOperationsInput | number
  avgResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  minResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ProbeHourlyStatUncheckedUpdateWithoutEndPointInput = {
  hourTimestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalChecks?: Prisma.IntFieldUpdateOperationsInput | number
  successCount?: Prisma.IntFieldUpdateOperationsInput | number
  avgResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  minResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ProbeHourlyStatUncheckedUpdateManyWithoutEndPointInput = {
  hourTimestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  totalChecks?: Prisma.IntFieldUpdateOperationsInput | number
  successCount?: Prisma.IntFieldUpdateOperationsInput | number
  avgResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  minResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxResponseTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}



export type ProbeHourlyStatSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  endPointId?: boolean
  hourTimestamp?: boolean
  totalChecks?: boolean
  successCount?: boolean
  avgResponseTime?: boolean
  minResponseTime?: boolean
  maxResponseTime?: boolean
  endPoint?: boolean | Prisma.EndPointDefaultArgs<ExtArgs>
}, ExtArgs["result"]["probeHourlyStat"]>

export type ProbeHourlyStatSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  endPointId?: boolean
  hourTimestamp?: boolean
  totalChecks?: boolean
  successCount?: boolean
  avgResponseTime?: boolean
  minResponseTime?: boolean
  maxResponseTime?: boolean
  endPoint?: boolean | Prisma.EndPointDefaultArgs<ExtArgs>
}, ExtArgs["result"]["probeHourlyStat"]>

export type ProbeHourlyStatSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  endPointId?: boolean
  hourTimestamp?: boolean
  totalChecks?: boolean
  successCount?: boolean
  avgResponseTime?: boolean
  minResponseTime?: boolean
  maxResponseTime?: boolean
  endPoint?: boolean | Prisma.EndPointDefaultArgs<ExtArgs>
}, ExtArgs["result"]["probeHourlyStat"]>

export type ProbeHourlyStatSelectScalar = {
  endPointId?: boolean
  hourTimestamp?: boolean
  totalChecks?: boolean
  successCount?: boolean
  avgResponseTime?: boolean
  minResponseTime?: boolean
  maxResponseTime?: boolean
}

export type ProbeHourlyStatOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"endPointId" | "hourTimestamp" | "totalChecks" | "successCount" | "avgResponseTime" | "minResponseTime" | "maxResponseTime", ExtArgs["result"]["probeHourlyStat"]>
export type ProbeHourlyStatInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  endPoint?: boolean | Prisma.EndPointDefaultArgs<ExtArgs>
}
export type ProbeHourlyStatIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  endPoint?: boolean | Prisma.EndPointDefaultArgs<ExtArgs>
}
export type ProbeHourlyStatIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  endPoint?: boolean | Prisma.EndPointDefaultArgs<ExtArgs>
}

export type $ProbeHourlyStatPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProbeHourlyStat"
  objects: {
    endPoint: Prisma.$EndPointPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    endPointId: string
    hourTimestamp: Date
    totalChecks: number
    successCount: number
    avgResponseTime: number | null
    minResponseTime: number | null
    maxResponseTime: number | null
  }, ExtArgs["result"]["probeHourlyStat"]>
  composites: {}
}

export type ProbeHourlyStatGetPayload<S extends boolean | null | undefined | ProbeHourlyStatDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProbeHourlyStatPayload, S>

export type ProbeHourlyStatCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProbeHourlyStatFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProbeHourlyStatCountAggregateInputType | true
  }

export interface ProbeHourlyStatDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProbeHourlyStat'], meta: { name: 'ProbeHourlyStat' } }
  /**
   * Find zero or one ProbeHourlyStat that matches the filter.
   * @param {ProbeHourlyStatFindUniqueArgs} args - Arguments to find a ProbeHourlyStat
   * @example
   * // Get one ProbeHourlyStat
   * const probeHourlyStat = await prisma.probeHourlyStat.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProbeHourlyStatFindUniqueArgs>(args: Prisma.SelectSubset<T, ProbeHourlyStatFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProbeHourlyStatClient<runtime.Types.Result.GetResult<Prisma.$ProbeHourlyStatPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProbeHourlyStat that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProbeHourlyStatFindUniqueOrThrowArgs} args - Arguments to find a ProbeHourlyStat
   * @example
   * // Get one ProbeHourlyStat
   * const probeHourlyStat = await prisma.probeHourlyStat.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProbeHourlyStatFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProbeHourlyStatFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProbeHourlyStatClient<runtime.Types.Result.GetResult<Prisma.$ProbeHourlyStatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProbeHourlyStat that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProbeHourlyStatFindFirstArgs} args - Arguments to find a ProbeHourlyStat
   * @example
   * // Get one ProbeHourlyStat
   * const probeHourlyStat = await prisma.probeHourlyStat.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProbeHourlyStatFindFirstArgs>(args?: Prisma.SelectSubset<T, ProbeHourlyStatFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProbeHourlyStatClient<runtime.Types.Result.GetResult<Prisma.$ProbeHourlyStatPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProbeHourlyStat that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProbeHourlyStatFindFirstOrThrowArgs} args - Arguments to find a ProbeHourlyStat
   * @example
   * // Get one ProbeHourlyStat
   * const probeHourlyStat = await prisma.probeHourlyStat.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProbeHourlyStatFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProbeHourlyStatFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProbeHourlyStatClient<runtime.Types.Result.GetResult<Prisma.$ProbeHourlyStatPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProbeHourlyStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProbeHourlyStatFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProbeHourlyStats
   * const probeHourlyStats = await prisma.probeHourlyStat.findMany()
   * 
   * // Get first 10 ProbeHourlyStats
   * const probeHourlyStats = await prisma.probeHourlyStat.findMany({ take: 10 })
   * 
   * // Only select the `endPointId`
   * const probeHourlyStatWithEndPointIdOnly = await prisma.probeHourlyStat.findMany({ select: { endPointId: true } })
   * 
   */
  findMany<T extends ProbeHourlyStatFindManyArgs>(args?: Prisma.SelectSubset<T, ProbeHourlyStatFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProbeHourlyStatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProbeHourlyStat.
   * @param {ProbeHourlyStatCreateArgs} args - Arguments to create a ProbeHourlyStat.
   * @example
   * // Create one ProbeHourlyStat
   * const ProbeHourlyStat = await prisma.probeHourlyStat.create({
   *   data: {
   *     // ... data to create a ProbeHourlyStat
   *   }
   * })
   * 
   */
  create<T extends ProbeHourlyStatCreateArgs>(args: Prisma.SelectSubset<T, ProbeHourlyStatCreateArgs<ExtArgs>>): Prisma.Prisma__ProbeHourlyStatClient<runtime.Types.Result.GetResult<Prisma.$ProbeHourlyStatPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProbeHourlyStats.
   * @param {ProbeHourlyStatCreateManyArgs} args - Arguments to create many ProbeHourlyStats.
   * @example
   * // Create many ProbeHourlyStats
   * const probeHourlyStat = await prisma.probeHourlyStat.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProbeHourlyStatCreateManyArgs>(args?: Prisma.SelectSubset<T, ProbeHourlyStatCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProbeHourlyStats and returns the data saved in the database.
   * @param {ProbeHourlyStatCreateManyAndReturnArgs} args - Arguments to create many ProbeHourlyStats.
   * @example
   * // Create many ProbeHourlyStats
   * const probeHourlyStat = await prisma.probeHourlyStat.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProbeHourlyStats and only return the `endPointId`
   * const probeHourlyStatWithEndPointIdOnly = await prisma.probeHourlyStat.createManyAndReturn({
   *   select: { endPointId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProbeHourlyStatCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProbeHourlyStatCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProbeHourlyStatPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProbeHourlyStat.
   * @param {ProbeHourlyStatDeleteArgs} args - Arguments to delete one ProbeHourlyStat.
   * @example
   * // Delete one ProbeHourlyStat
   * const ProbeHourlyStat = await prisma.probeHourlyStat.delete({
   *   where: {
   *     // ... filter to delete one ProbeHourlyStat
   *   }
   * })
   * 
   */
  delete<T extends ProbeHourlyStatDeleteArgs>(args: Prisma.SelectSubset<T, ProbeHourlyStatDeleteArgs<ExtArgs>>): Prisma.Prisma__ProbeHourlyStatClient<runtime.Types.Result.GetResult<Prisma.$ProbeHourlyStatPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProbeHourlyStat.
   * @param {ProbeHourlyStatUpdateArgs} args - Arguments to update one ProbeHourlyStat.
   * @example
   * // Update one ProbeHourlyStat
   * const probeHourlyStat = await prisma.probeHourlyStat.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProbeHourlyStatUpdateArgs>(args: Prisma.SelectSubset<T, ProbeHourlyStatUpdateArgs<ExtArgs>>): Prisma.Prisma__ProbeHourlyStatClient<runtime.Types.Result.GetResult<Prisma.$ProbeHourlyStatPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProbeHourlyStats.
   * @param {ProbeHourlyStatDeleteManyArgs} args - Arguments to filter ProbeHourlyStats to delete.
   * @example
   * // Delete a few ProbeHourlyStats
   * const { count } = await prisma.probeHourlyStat.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProbeHourlyStatDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProbeHourlyStatDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProbeHourlyStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProbeHourlyStatUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProbeHourlyStats
   * const probeHourlyStat = await prisma.probeHourlyStat.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProbeHourlyStatUpdateManyArgs>(args: Prisma.SelectSubset<T, ProbeHourlyStatUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProbeHourlyStats and returns the data updated in the database.
   * @param {ProbeHourlyStatUpdateManyAndReturnArgs} args - Arguments to update many ProbeHourlyStats.
   * @example
   * // Update many ProbeHourlyStats
   * const probeHourlyStat = await prisma.probeHourlyStat.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProbeHourlyStats and only return the `endPointId`
   * const probeHourlyStatWithEndPointIdOnly = await prisma.probeHourlyStat.updateManyAndReturn({
   *   select: { endPointId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProbeHourlyStatUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProbeHourlyStatUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProbeHourlyStatPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProbeHourlyStat.
   * @param {ProbeHourlyStatUpsertArgs} args - Arguments to update or create a ProbeHourlyStat.
   * @example
   * // Update or create a ProbeHourlyStat
   * const probeHourlyStat = await prisma.probeHourlyStat.upsert({
   *   create: {
   *     // ... data to create a ProbeHourlyStat
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProbeHourlyStat we want to update
   *   }
   * })
   */
  upsert<T extends ProbeHourlyStatUpsertArgs>(args: Prisma.SelectSubset<T, ProbeHourlyStatUpsertArgs<ExtArgs>>): Prisma.Prisma__ProbeHourlyStatClient<runtime.Types.Result.GetResult<Prisma.$ProbeHourlyStatPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProbeHourlyStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProbeHourlyStatCountArgs} args - Arguments to filter ProbeHourlyStats to count.
   * @example
   * // Count the number of ProbeHourlyStats
   * const count = await prisma.probeHourlyStat.count({
   *   where: {
   *     // ... the filter for the ProbeHourlyStats we want to count
   *   }
   * })
  **/
  count<T extends ProbeHourlyStatCountArgs>(
    args?: Prisma.Subset<T, ProbeHourlyStatCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProbeHourlyStatCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProbeHourlyStat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProbeHourlyStatAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProbeHourlyStatAggregateArgs>(args: Prisma.Subset<T, ProbeHourlyStatAggregateArgs>): Prisma.PrismaPromise<GetProbeHourlyStatAggregateType<T>>

  /**
   * Group by ProbeHourlyStat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProbeHourlyStatGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProbeHourlyStatGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProbeHourlyStatGroupByArgs['orderBy'] }
      : { orderBy?: ProbeHourlyStatGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProbeHourlyStatGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProbeHourlyStatGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProbeHourlyStat model
 */
readonly fields: ProbeHourlyStatFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProbeHourlyStat.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProbeHourlyStatClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  endPoint<T extends Prisma.EndPointDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EndPointDefaultArgs<ExtArgs>>): Prisma.Prisma__EndPointClient<runtime.Types.Result.GetResult<Prisma.$EndPointPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProbeHourlyStat model
 */
export interface ProbeHourlyStatFieldRefs {
  readonly endPointId: Prisma.FieldRef<"ProbeHourlyStat", 'String'>
  readonly hourTimestamp: Prisma.FieldRef<"ProbeHourlyStat", 'DateTime'>
  readonly totalChecks: Prisma.FieldRef<"ProbeHourlyStat", 'Int'>
  readonly successCount: Prisma.FieldRef<"ProbeHourlyStat", 'Int'>
  readonly avgResponseTime: Prisma.FieldRef<"ProbeHourlyStat", 'Int'>
  readonly minResponseTime: Prisma.FieldRef<"ProbeHourlyStat", 'Int'>
  readonly maxResponseTime: Prisma.FieldRef<"ProbeHourlyStat", 'Int'>
}
    

// Custom InputTypes
/**
 * ProbeHourlyStat findUnique
 */
export type ProbeHourlyStatFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProbeHourlyStat
   */
  select?: Prisma.ProbeHourlyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProbeHourlyStat
   */
  omit?: Prisma.ProbeHourlyStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProbeHourlyStatInclude<ExtArgs> | null
  /**
   * Filter, which ProbeHourlyStat to fetch.
   */
  where: Prisma.ProbeHourlyStatWhereUniqueInput
}

/**
 * ProbeHourlyStat findUniqueOrThrow
 */
export type ProbeHourlyStatFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProbeHourlyStat
   */
  select?: Prisma.ProbeHourlyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProbeHourlyStat
   */
  omit?: Prisma.ProbeHourlyStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProbeHourlyStatInclude<ExtArgs> | null
  /**
   * Filter, which ProbeHourlyStat to fetch.
   */
  where: Prisma.ProbeHourlyStatWhereUniqueInput
}

/**
 * ProbeHourlyStat findFirst
 */
export type ProbeHourlyStatFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProbeHourlyStat
   */
  select?: Prisma.ProbeHourlyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProbeHourlyStat
   */
  omit?: Prisma.ProbeHourlyStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProbeHourlyStatInclude<ExtArgs> | null
  /**
   * Filter, which ProbeHourlyStat to fetch.
   */
  where?: Prisma.ProbeHourlyStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProbeHourlyStats to fetch.
   */
  orderBy?: Prisma.ProbeHourlyStatOrderByWithRelationInput | Prisma.ProbeHourlyStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProbeHourlyStats.
   */
  cursor?: Prisma.ProbeHourlyStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProbeHourlyStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProbeHourlyStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProbeHourlyStats.
   */
  distinct?: Prisma.ProbeHourlyStatScalarFieldEnum | Prisma.ProbeHourlyStatScalarFieldEnum[]
}

/**
 * ProbeHourlyStat findFirstOrThrow
 */
export type ProbeHourlyStatFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProbeHourlyStat
   */
  select?: Prisma.ProbeHourlyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProbeHourlyStat
   */
  omit?: Prisma.ProbeHourlyStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProbeHourlyStatInclude<ExtArgs> | null
  /**
   * Filter, which ProbeHourlyStat to fetch.
   */
  where?: Prisma.ProbeHourlyStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProbeHourlyStats to fetch.
   */
  orderBy?: Prisma.ProbeHourlyStatOrderByWithRelationInput | Prisma.ProbeHourlyStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProbeHourlyStats.
   */
  cursor?: Prisma.ProbeHourlyStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProbeHourlyStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProbeHourlyStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProbeHourlyStats.
   */
  distinct?: Prisma.ProbeHourlyStatScalarFieldEnum | Prisma.ProbeHourlyStatScalarFieldEnum[]
}

/**
 * ProbeHourlyStat findMany
 */
export type ProbeHourlyStatFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProbeHourlyStat
   */
  select?: Prisma.ProbeHourlyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProbeHourlyStat
   */
  omit?: Prisma.ProbeHourlyStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProbeHourlyStatInclude<ExtArgs> | null
  /**
   * Filter, which ProbeHourlyStats to fetch.
   */
  where?: Prisma.ProbeHourlyStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProbeHourlyStats to fetch.
   */
  orderBy?: Prisma.ProbeHourlyStatOrderByWithRelationInput | Prisma.ProbeHourlyStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProbeHourlyStats.
   */
  cursor?: Prisma.ProbeHourlyStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProbeHourlyStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProbeHourlyStats.
   */
  skip?: number
  distinct?: Prisma.ProbeHourlyStatScalarFieldEnum | Prisma.ProbeHourlyStatScalarFieldEnum[]
}

/**
 * ProbeHourlyStat create
 */
export type ProbeHourlyStatCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProbeHourlyStat
   */
  select?: Prisma.ProbeHourlyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProbeHourlyStat
   */
  omit?: Prisma.ProbeHourlyStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProbeHourlyStatInclude<ExtArgs> | null
  /**
   * The data needed to create a ProbeHourlyStat.
   */
  data: Prisma.XOR<Prisma.ProbeHourlyStatCreateInput, Prisma.ProbeHourlyStatUncheckedCreateInput>
}

/**
 * ProbeHourlyStat createMany
 */
export type ProbeHourlyStatCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProbeHourlyStats.
   */
  data: Prisma.ProbeHourlyStatCreateManyInput | Prisma.ProbeHourlyStatCreateManyInput[]
}

/**
 * ProbeHourlyStat createManyAndReturn
 */
export type ProbeHourlyStatCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProbeHourlyStat
   */
  select?: Prisma.ProbeHourlyStatSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProbeHourlyStat
   */
  omit?: Prisma.ProbeHourlyStatOmit<ExtArgs> | null
  /**
   * The data used to create many ProbeHourlyStats.
   */
  data: Prisma.ProbeHourlyStatCreateManyInput | Prisma.ProbeHourlyStatCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProbeHourlyStatIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProbeHourlyStat update
 */
export type ProbeHourlyStatUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProbeHourlyStat
   */
  select?: Prisma.ProbeHourlyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProbeHourlyStat
   */
  omit?: Prisma.ProbeHourlyStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProbeHourlyStatInclude<ExtArgs> | null
  /**
   * The data needed to update a ProbeHourlyStat.
   */
  data: Prisma.XOR<Prisma.ProbeHourlyStatUpdateInput, Prisma.ProbeHourlyStatUncheckedUpdateInput>
  /**
   * Choose, which ProbeHourlyStat to update.
   */
  where: Prisma.ProbeHourlyStatWhereUniqueInput
}

/**
 * ProbeHourlyStat updateMany
 */
export type ProbeHourlyStatUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProbeHourlyStats.
   */
  data: Prisma.XOR<Prisma.ProbeHourlyStatUpdateManyMutationInput, Prisma.ProbeHourlyStatUncheckedUpdateManyInput>
  /**
   * Filter which ProbeHourlyStats to update
   */
  where?: Prisma.ProbeHourlyStatWhereInput
  /**
   * Limit how many ProbeHourlyStats to update.
   */
  limit?: number
}

/**
 * ProbeHourlyStat updateManyAndReturn
 */
export type ProbeHourlyStatUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProbeHourlyStat
   */
  select?: Prisma.ProbeHourlyStatSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProbeHourlyStat
   */
  omit?: Prisma.ProbeHourlyStatOmit<ExtArgs> | null
  /**
   * The data used to update ProbeHourlyStats.
   */
  data: Prisma.XOR<Prisma.ProbeHourlyStatUpdateManyMutationInput, Prisma.ProbeHourlyStatUncheckedUpdateManyInput>
  /**
   * Filter which ProbeHourlyStats to update
   */
  where?: Prisma.ProbeHourlyStatWhereInput
  /**
   * Limit how many ProbeHourlyStats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProbeHourlyStatIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProbeHourlyStat upsert
 */
export type ProbeHourlyStatUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProbeHourlyStat
   */
  select?: Prisma.ProbeHourlyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProbeHourlyStat
   */
  omit?: Prisma.ProbeHourlyStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProbeHourlyStatInclude<ExtArgs> | null
  /**
   * The filter to search for the ProbeHourlyStat to update in case it exists.
   */
  where: Prisma.ProbeHourlyStatWhereUniqueInput
  /**
   * In case the ProbeHourlyStat found by the `where` argument doesn't exist, create a new ProbeHourlyStat with this data.
   */
  create: Prisma.XOR<Prisma.ProbeHourlyStatCreateInput, Prisma.ProbeHourlyStatUncheckedCreateInput>
  /**
   * In case the ProbeHourlyStat was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProbeHourlyStatUpdateInput, Prisma.ProbeHourlyStatUncheckedUpdateInput>
}

/**
 * ProbeHourlyStat delete
 */
export type ProbeHourlyStatDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProbeHourlyStat
   */
  select?: Prisma.ProbeHourlyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProbeHourlyStat
   */
  omit?: Prisma.ProbeHourlyStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProbeHourlyStatInclude<ExtArgs> | null
  /**
   * Filter which ProbeHourlyStat to delete.
   */
  where: Prisma.ProbeHourlyStatWhereUniqueInput
}

/**
 * ProbeHourlyStat deleteMany
 */
export type ProbeHourlyStatDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProbeHourlyStats to delete
   */
  where?: Prisma.ProbeHourlyStatWhereInput
  /**
   * Limit how many ProbeHourlyStats to delete.
   */
  limit?: number
}

/**
 * ProbeHourlyStat without action
 */
export type ProbeHourlyStatDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProbeHourlyStat
   */
  select?: Prisma.ProbeHourlyStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProbeHourlyStat
   */
  omit?: Prisma.ProbeHourlyStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProbeHourlyStatInclude<ExtArgs> | null
}
