
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TagGroup` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TagGroup
 * 
 */
export type TagGroupModel = runtime.Types.Result.DefaultSelection<Prisma.$TagGroupPayload>

export type AggregateTagGroup = {
  _count: TagGroupCountAggregateOutputType | null
  _min: TagGroupMinAggregateOutputType | null
  _max: TagGroupMaxAggregateOutputType | null
}

export type TagGroupMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  title: string | null
}

export type TagGroupMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  title: string | null
}

export type TagGroupCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  title: number
  _all: number
}


export type TagGroupMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  title?: true
}

export type TagGroupMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  title?: true
}

export type TagGroupCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  title?: true
  _all?: true
}

export type TagGroupAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TagGroup to aggregate.
   */
  where?: Prisma.TagGroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagGroups to fetch.
   */
  orderBy?: Prisma.TagGroupOrderByWithRelationInput | Prisma.TagGroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TagGroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagGroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagGroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TagGroups
  **/
  _count?: true | TagGroupCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TagGroupMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TagGroupMaxAggregateInputType
}

export type GetTagGroupAggregateType<T extends TagGroupAggregateArgs> = {
      [P in keyof T & keyof AggregateTagGroup]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTagGroup[P]>
    : Prisma.GetScalarType<T[P], AggregateTagGroup[P]>
}




export type TagGroupGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TagGroupWhereInput
  orderBy?: Prisma.TagGroupOrderByWithAggregationInput | Prisma.TagGroupOrderByWithAggregationInput[]
  by: Prisma.TagGroupScalarFieldEnum[] | Prisma.TagGroupScalarFieldEnum
  having?: Prisma.TagGroupScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TagGroupCountAggregateInputType | true
  _min?: TagGroupMinAggregateInputType
  _max?: TagGroupMaxAggregateInputType
}

export type TagGroupGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  title: string
  _count: TagGroupCountAggregateOutputType | null
  _min: TagGroupMinAggregateOutputType | null
  _max: TagGroupMaxAggregateOutputType | null
}

type GetTagGroupGroupByPayload<T extends TagGroupGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TagGroupGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TagGroupGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TagGroupGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TagGroupGroupByOutputType[P]>
      }
    >
  >



export type TagGroupWhereInput = {
  AND?: Prisma.TagGroupWhereInput | Prisma.TagGroupWhereInput[]
  OR?: Prisma.TagGroupWhereInput[]
  NOT?: Prisma.TagGroupWhereInput | Prisma.TagGroupWhereInput[]
  id?: Prisma.StringFilter<"TagGroup"> | string
  createdAt?: Prisma.DateTimeFilter<"TagGroup"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TagGroup"> | Date | string
  title?: Prisma.StringFilter<"TagGroup"> | string
  tags?: Prisma.TagListRelationFilter
}

export type TagGroupOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  title?: Prisma.SortOrder
  tags?: Prisma.TagOrderByRelationAggregateInput
}

export type TagGroupWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  title?: string
  AND?: Prisma.TagGroupWhereInput | Prisma.TagGroupWhereInput[]
  OR?: Prisma.TagGroupWhereInput[]
  NOT?: Prisma.TagGroupWhereInput | Prisma.TagGroupWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"TagGroup"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TagGroup"> | Date | string
  tags?: Prisma.TagListRelationFilter
}, "id" | "title">

export type TagGroupOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  title?: Prisma.SortOrder
  _count?: Prisma.TagGroupCountOrderByAggregateInput
  _max?: Prisma.TagGroupMaxOrderByAggregateInput
  _min?: Prisma.TagGroupMinOrderByAggregateInput
}

export type TagGroupScalarWhereWithAggregatesInput = {
  AND?: Prisma.TagGroupScalarWhereWithAggregatesInput | Prisma.TagGroupScalarWhereWithAggregatesInput[]
  OR?: Prisma.TagGroupScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TagGroupScalarWhereWithAggregatesInput | Prisma.TagGroupScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TagGroup"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TagGroup"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TagGroup"> | Date | string
  title?: Prisma.StringWithAggregatesFilter<"TagGroup"> | string
}

export type TagGroupCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  title: string
  tags?: Prisma.TagCreateNestedManyWithoutGroupInput
}

export type TagGroupUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  title: string
  tags?: Prisma.TagUncheckedCreateNestedManyWithoutGroupInput
}

export type TagGroupUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.TagUpdateManyWithoutGroupNestedInput
}

export type TagGroupUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.TagUncheckedUpdateManyWithoutGroupNestedInput
}

export type TagGroupCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  title: string
}

export type TagGroupUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TagGroupUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TagGroupNullableScalarRelationFilter = {
  is?: Prisma.TagGroupWhereInput | null
  isNot?: Prisma.TagGroupWhereInput | null
}

export type TagGroupCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  title?: Prisma.SortOrder
}

export type TagGroupMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  title?: Prisma.SortOrder
}

export type TagGroupMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  title?: Prisma.SortOrder
}

export type TagGroupCreateNestedOneWithoutTagsInput = {
  create?: Prisma.XOR<Prisma.TagGroupCreateWithoutTagsInput, Prisma.TagGroupUncheckedCreateWithoutTagsInput>
  connectOrCreate?: Prisma.TagGroupCreateOrConnectWithoutTagsInput
  connect?: Prisma.TagGroupWhereUniqueInput
}

export type TagGroupUpdateOneWithoutTagsNestedInput = {
  create?: Prisma.XOR<Prisma.TagGroupCreateWithoutTagsInput, Prisma.TagGroupUncheckedCreateWithoutTagsInput>
  connectOrCreate?: Prisma.TagGroupCreateOrConnectWithoutTagsInput
  upsert?: Prisma.TagGroupUpsertWithoutTagsInput
  disconnect?: Prisma.TagGroupWhereInput | boolean
  delete?: Prisma.TagGroupWhereInput | boolean
  connect?: Prisma.TagGroupWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TagGroupUpdateToOneWithWhereWithoutTagsInput, Prisma.TagGroupUpdateWithoutTagsInput>, Prisma.TagGroupUncheckedUpdateWithoutTagsInput>
}

export type TagGroupCreateWithoutTagsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  title: string
}

export type TagGroupUncheckedCreateWithoutTagsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  title: string
}

export type TagGroupCreateOrConnectWithoutTagsInput = {
  where: Prisma.TagGroupWhereUniqueInput
  create: Prisma.XOR<Prisma.TagGroupCreateWithoutTagsInput, Prisma.TagGroupUncheckedCreateWithoutTagsInput>
}

export type TagGroupUpsertWithoutTagsInput = {
  update: Prisma.XOR<Prisma.TagGroupUpdateWithoutTagsInput, Prisma.TagGroupUncheckedUpdateWithoutTagsInput>
  create: Prisma.XOR<Prisma.TagGroupCreateWithoutTagsInput, Prisma.TagGroupUncheckedCreateWithoutTagsInput>
  where?: Prisma.TagGroupWhereInput
}

export type TagGroupUpdateToOneWithWhereWithoutTagsInput = {
  where?: Prisma.TagGroupWhereInput
  data: Prisma.XOR<Prisma.TagGroupUpdateWithoutTagsInput, Prisma.TagGroupUncheckedUpdateWithoutTagsInput>
}

export type TagGroupUpdateWithoutTagsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TagGroupUncheckedUpdateWithoutTagsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type TagGroupCountOutputType
 */

export type TagGroupCountOutputType = {
  tags: number
}

export type TagGroupCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tags?: boolean | TagGroupCountOutputTypeCountTagsArgs
}

/**
 * TagGroupCountOutputType without action
 */
export type TagGroupCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagGroupCountOutputType
   */
  select?: Prisma.TagGroupCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TagGroupCountOutputType without action
 */
export type TagGroupCountOutputTypeCountTagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TagWhereInput
}


export type TagGroupSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  title?: boolean
  tags?: boolean | Prisma.TagGroup$tagsArgs<ExtArgs>
  _count?: boolean | Prisma.TagGroupCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tagGroup"]>

export type TagGroupSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  title?: boolean
}, ExtArgs["result"]["tagGroup"]>

export type TagGroupSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  title?: boolean
}, ExtArgs["result"]["tagGroup"]>

export type TagGroupSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  title?: boolean
}

export type TagGroupOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "title", ExtArgs["result"]["tagGroup"]>
export type TagGroupInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tags?: boolean | Prisma.TagGroup$tagsArgs<ExtArgs>
  _count?: boolean | Prisma.TagGroupCountOutputTypeDefaultArgs<ExtArgs>
}
export type TagGroupIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type TagGroupIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $TagGroupPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TagGroup"
  objects: {
    tags: Prisma.$TagPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    title: string
  }, ExtArgs["result"]["tagGroup"]>
  composites: {}
}

export type TagGroupGetPayload<S extends boolean | null | undefined | TagGroupDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TagGroupPayload, S>

export type TagGroupCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TagGroupFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TagGroupCountAggregateInputType | true
  }

export interface TagGroupDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TagGroup'], meta: { name: 'TagGroup' } }
  /**
   * Find zero or one TagGroup that matches the filter.
   * @param {TagGroupFindUniqueArgs} args - Arguments to find a TagGroup
   * @example
   * // Get one TagGroup
   * const tagGroup = await prisma.tagGroup.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TagGroupFindUniqueArgs>(args: Prisma.SelectSubset<T, TagGroupFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TagGroupClient<runtime.Types.Result.GetResult<Prisma.$TagGroupPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TagGroup that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TagGroupFindUniqueOrThrowArgs} args - Arguments to find a TagGroup
   * @example
   * // Get one TagGroup
   * const tagGroup = await prisma.tagGroup.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TagGroupFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TagGroupFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TagGroupClient<runtime.Types.Result.GetResult<Prisma.$TagGroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TagGroup that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagGroupFindFirstArgs} args - Arguments to find a TagGroup
   * @example
   * // Get one TagGroup
   * const tagGroup = await prisma.tagGroup.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TagGroupFindFirstArgs>(args?: Prisma.SelectSubset<T, TagGroupFindFirstArgs<ExtArgs>>): Prisma.Prisma__TagGroupClient<runtime.Types.Result.GetResult<Prisma.$TagGroupPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TagGroup that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagGroupFindFirstOrThrowArgs} args - Arguments to find a TagGroup
   * @example
   * // Get one TagGroup
   * const tagGroup = await prisma.tagGroup.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TagGroupFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TagGroupFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TagGroupClient<runtime.Types.Result.GetResult<Prisma.$TagGroupPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TagGroups that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagGroupFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TagGroups
   * const tagGroups = await prisma.tagGroup.findMany()
   * 
   * // Get first 10 TagGroups
   * const tagGroups = await prisma.tagGroup.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tagGroupWithIdOnly = await prisma.tagGroup.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TagGroupFindManyArgs>(args?: Prisma.SelectSubset<T, TagGroupFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagGroupPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TagGroup.
   * @param {TagGroupCreateArgs} args - Arguments to create a TagGroup.
   * @example
   * // Create one TagGroup
   * const TagGroup = await prisma.tagGroup.create({
   *   data: {
   *     // ... data to create a TagGroup
   *   }
   * })
   * 
   */
  create<T extends TagGroupCreateArgs>(args: Prisma.SelectSubset<T, TagGroupCreateArgs<ExtArgs>>): Prisma.Prisma__TagGroupClient<runtime.Types.Result.GetResult<Prisma.$TagGroupPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TagGroups.
   * @param {TagGroupCreateManyArgs} args - Arguments to create many TagGroups.
   * @example
   * // Create many TagGroups
   * const tagGroup = await prisma.tagGroup.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TagGroupCreateManyArgs>(args?: Prisma.SelectSubset<T, TagGroupCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TagGroups and returns the data saved in the database.
   * @param {TagGroupCreateManyAndReturnArgs} args - Arguments to create many TagGroups.
   * @example
   * // Create many TagGroups
   * const tagGroup = await prisma.tagGroup.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TagGroups and only return the `id`
   * const tagGroupWithIdOnly = await prisma.tagGroup.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TagGroupCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TagGroupCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagGroupPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TagGroup.
   * @param {TagGroupDeleteArgs} args - Arguments to delete one TagGroup.
   * @example
   * // Delete one TagGroup
   * const TagGroup = await prisma.tagGroup.delete({
   *   where: {
   *     // ... filter to delete one TagGroup
   *   }
   * })
   * 
   */
  delete<T extends TagGroupDeleteArgs>(args: Prisma.SelectSubset<T, TagGroupDeleteArgs<ExtArgs>>): Prisma.Prisma__TagGroupClient<runtime.Types.Result.GetResult<Prisma.$TagGroupPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TagGroup.
   * @param {TagGroupUpdateArgs} args - Arguments to update one TagGroup.
   * @example
   * // Update one TagGroup
   * const tagGroup = await prisma.tagGroup.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TagGroupUpdateArgs>(args: Prisma.SelectSubset<T, TagGroupUpdateArgs<ExtArgs>>): Prisma.Prisma__TagGroupClient<runtime.Types.Result.GetResult<Prisma.$TagGroupPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TagGroups.
   * @param {TagGroupDeleteManyArgs} args - Arguments to filter TagGroups to delete.
   * @example
   * // Delete a few TagGroups
   * const { count } = await prisma.tagGroup.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TagGroupDeleteManyArgs>(args?: Prisma.SelectSubset<T, TagGroupDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TagGroups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagGroupUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TagGroups
   * const tagGroup = await prisma.tagGroup.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TagGroupUpdateManyArgs>(args: Prisma.SelectSubset<T, TagGroupUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TagGroups and returns the data updated in the database.
   * @param {TagGroupUpdateManyAndReturnArgs} args - Arguments to update many TagGroups.
   * @example
   * // Update many TagGroups
   * const tagGroup = await prisma.tagGroup.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TagGroups and only return the `id`
   * const tagGroupWithIdOnly = await prisma.tagGroup.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TagGroupUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TagGroupUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagGroupPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TagGroup.
   * @param {TagGroupUpsertArgs} args - Arguments to update or create a TagGroup.
   * @example
   * // Update or create a TagGroup
   * const tagGroup = await prisma.tagGroup.upsert({
   *   create: {
   *     // ... data to create a TagGroup
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TagGroup we want to update
   *   }
   * })
   */
  upsert<T extends TagGroupUpsertArgs>(args: Prisma.SelectSubset<T, TagGroupUpsertArgs<ExtArgs>>): Prisma.Prisma__TagGroupClient<runtime.Types.Result.GetResult<Prisma.$TagGroupPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TagGroups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagGroupCountArgs} args - Arguments to filter TagGroups to count.
   * @example
   * // Count the number of TagGroups
   * const count = await prisma.tagGroup.count({
   *   where: {
   *     // ... the filter for the TagGroups we want to count
   *   }
   * })
  **/
  count<T extends TagGroupCountArgs>(
    args?: Prisma.Subset<T, TagGroupCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TagGroupCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TagGroup.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagGroupAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TagGroupAggregateArgs>(args: Prisma.Subset<T, TagGroupAggregateArgs>): Prisma.PrismaPromise<GetTagGroupAggregateType<T>>

  /**
   * Group by TagGroup.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagGroupGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TagGroupGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TagGroupGroupByArgs['orderBy'] }
      : { orderBy?: TagGroupGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TagGroupGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTagGroupGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TagGroup model
 */
readonly fields: TagGroupFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TagGroup.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TagGroupClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tags<T extends Prisma.TagGroup$tagsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TagGroup$tagsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TagGroup model
 */
export interface TagGroupFieldRefs {
  readonly id: Prisma.FieldRef<"TagGroup", 'String'>
  readonly createdAt: Prisma.FieldRef<"TagGroup", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TagGroup", 'DateTime'>
  readonly title: Prisma.FieldRef<"TagGroup", 'String'>
}
    

// Custom InputTypes
/**
 * TagGroup findUnique
 */
export type TagGroupFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagGroup
   */
  select?: Prisma.TagGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagGroup
   */
  omit?: Prisma.TagGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagGroupInclude<ExtArgs> | null
  /**
   * Filter, which TagGroup to fetch.
   */
  where: Prisma.TagGroupWhereUniqueInput
}

/**
 * TagGroup findUniqueOrThrow
 */
export type TagGroupFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagGroup
   */
  select?: Prisma.TagGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagGroup
   */
  omit?: Prisma.TagGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagGroupInclude<ExtArgs> | null
  /**
   * Filter, which TagGroup to fetch.
   */
  where: Prisma.TagGroupWhereUniqueInput
}

/**
 * TagGroup findFirst
 */
export type TagGroupFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagGroup
   */
  select?: Prisma.TagGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagGroup
   */
  omit?: Prisma.TagGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagGroupInclude<ExtArgs> | null
  /**
   * Filter, which TagGroup to fetch.
   */
  where?: Prisma.TagGroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagGroups to fetch.
   */
  orderBy?: Prisma.TagGroupOrderByWithRelationInput | Prisma.TagGroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TagGroups.
   */
  cursor?: Prisma.TagGroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagGroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagGroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagGroups.
   */
  distinct?: Prisma.TagGroupScalarFieldEnum | Prisma.TagGroupScalarFieldEnum[]
}

/**
 * TagGroup findFirstOrThrow
 */
export type TagGroupFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagGroup
   */
  select?: Prisma.TagGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagGroup
   */
  omit?: Prisma.TagGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagGroupInclude<ExtArgs> | null
  /**
   * Filter, which TagGroup to fetch.
   */
  where?: Prisma.TagGroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagGroups to fetch.
   */
  orderBy?: Prisma.TagGroupOrderByWithRelationInput | Prisma.TagGroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TagGroups.
   */
  cursor?: Prisma.TagGroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagGroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagGroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagGroups.
   */
  distinct?: Prisma.TagGroupScalarFieldEnum | Prisma.TagGroupScalarFieldEnum[]
}

/**
 * TagGroup findMany
 */
export type TagGroupFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagGroup
   */
  select?: Prisma.TagGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagGroup
   */
  omit?: Prisma.TagGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagGroupInclude<ExtArgs> | null
  /**
   * Filter, which TagGroups to fetch.
   */
  where?: Prisma.TagGroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagGroups to fetch.
   */
  orderBy?: Prisma.TagGroupOrderByWithRelationInput | Prisma.TagGroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TagGroups.
   */
  cursor?: Prisma.TagGroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagGroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagGroups.
   */
  skip?: number
  distinct?: Prisma.TagGroupScalarFieldEnum | Prisma.TagGroupScalarFieldEnum[]
}

/**
 * TagGroup create
 */
export type TagGroupCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagGroup
   */
  select?: Prisma.TagGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagGroup
   */
  omit?: Prisma.TagGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagGroupInclude<ExtArgs> | null
  /**
   * The data needed to create a TagGroup.
   */
  data: Prisma.XOR<Prisma.TagGroupCreateInput, Prisma.TagGroupUncheckedCreateInput>
}

/**
 * TagGroup createMany
 */
export type TagGroupCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TagGroups.
   */
  data: Prisma.TagGroupCreateManyInput | Prisma.TagGroupCreateManyInput[]
}

/**
 * TagGroup createManyAndReturn
 */
export type TagGroupCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagGroup
   */
  select?: Prisma.TagGroupSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TagGroup
   */
  omit?: Prisma.TagGroupOmit<ExtArgs> | null
  /**
   * The data used to create many TagGroups.
   */
  data: Prisma.TagGroupCreateManyInput | Prisma.TagGroupCreateManyInput[]
}

/**
 * TagGroup update
 */
export type TagGroupUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagGroup
   */
  select?: Prisma.TagGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagGroup
   */
  omit?: Prisma.TagGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagGroupInclude<ExtArgs> | null
  /**
   * The data needed to update a TagGroup.
   */
  data: Prisma.XOR<Prisma.TagGroupUpdateInput, Prisma.TagGroupUncheckedUpdateInput>
  /**
   * Choose, which TagGroup to update.
   */
  where: Prisma.TagGroupWhereUniqueInput
}

/**
 * TagGroup updateMany
 */
export type TagGroupUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TagGroups.
   */
  data: Prisma.XOR<Prisma.TagGroupUpdateManyMutationInput, Prisma.TagGroupUncheckedUpdateManyInput>
  /**
   * Filter which TagGroups to update
   */
  where?: Prisma.TagGroupWhereInput
  /**
   * Limit how many TagGroups to update.
   */
  limit?: number
}

/**
 * TagGroup updateManyAndReturn
 */
export type TagGroupUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagGroup
   */
  select?: Prisma.TagGroupSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TagGroup
   */
  omit?: Prisma.TagGroupOmit<ExtArgs> | null
  /**
   * The data used to update TagGroups.
   */
  data: Prisma.XOR<Prisma.TagGroupUpdateManyMutationInput, Prisma.TagGroupUncheckedUpdateManyInput>
  /**
   * Filter which TagGroups to update
   */
  where?: Prisma.TagGroupWhereInput
  /**
   * Limit how many TagGroups to update.
   */
  limit?: number
}

/**
 * TagGroup upsert
 */
export type TagGroupUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagGroup
   */
  select?: Prisma.TagGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagGroup
   */
  omit?: Prisma.TagGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagGroupInclude<ExtArgs> | null
  /**
   * The filter to search for the TagGroup to update in case it exists.
   */
  where: Prisma.TagGroupWhereUniqueInput
  /**
   * In case the TagGroup found by the `where` argument doesn't exist, create a new TagGroup with this data.
   */
  create: Prisma.XOR<Prisma.TagGroupCreateInput, Prisma.TagGroupUncheckedCreateInput>
  /**
   * In case the TagGroup was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TagGroupUpdateInput, Prisma.TagGroupUncheckedUpdateInput>
}

/**
 * TagGroup delete
 */
export type TagGroupDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagGroup
   */
  select?: Prisma.TagGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagGroup
   */
  omit?: Prisma.TagGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagGroupInclude<ExtArgs> | null
  /**
   * Filter which TagGroup to delete.
   */
  where: Prisma.TagGroupWhereUniqueInput
}

/**
 * TagGroup deleteMany
 */
export type TagGroupDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TagGroups to delete
   */
  where?: Prisma.TagGroupWhereInput
  /**
   * Limit how many TagGroups to delete.
   */
  limit?: number
}

/**
 * TagGroup.tags
 */
export type TagGroup$tagsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tag
   */
  select?: Prisma.TagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tag
   */
  omit?: Prisma.TagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagInclude<ExtArgs> | null
  where?: Prisma.TagWhereInput
  orderBy?: Prisma.TagOrderByWithRelationInput | Prisma.TagOrderByWithRelationInput[]
  cursor?: Prisma.TagWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TagScalarFieldEnum | Prisma.TagScalarFieldEnum[]
}

/**
 * TagGroup without action
 */
export type TagGroupDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagGroup
   */
  select?: Prisma.TagGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagGroup
   */
  omit?: Prisma.TagGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagGroupInclude<ExtArgs> | null
}
