
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Attachment
 * 
 */
export type Attachment = Prisma.AttachmentModel
/**
 * Model Application
 * 
 */
export type Application = Prisma.ApplicationModel
/**
 * Model WebAuthnCredential
 * 
 */
export type WebAuthnCredential = Prisma.WebAuthnCredentialModel
/**
 * Model AppConfig
 * 
 */
export type AppConfig = Prisma.AppConfigModel
/**
 * Model MonitoredHost
 * 
 */
export type MonitoredHost = Prisma.MonitoredHostModel
/**
 * Model EndPoint
 * 
 */
export type EndPoint = Prisma.EndPointModel
/**
 * Model ProbeResult
 * 
 */
export type ProbeResult = Prisma.ProbeResultModel
/**
 * Model ProbeHourlyStat
 * 
 */
export type ProbeHourlyStat = Prisma.ProbeHourlyStatModel
/**
 * Model ProbeDailyStat
 * 
 */
export type ProbeDailyStat = Prisma.ProbeDailyStatModel
/**
 * Model NotificationChannel
 * 
 */
export type NotificationChannel = Prisma.NotificationChannelModel
/**
 * Model NotificationLog
 * 
 */
export type NotificationLog = Prisma.NotificationLogModel
/**
 * Model ProbeEnv
 * 
 */
export type ProbeEnv = Prisma.ProbeEnvModel
