
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/AppConfig'
export type * from './models/Attachment'
export type * from './models/MonitoredHost'
export type * from './models/EndPoint'
export type * from './models/ProbeResult'
export type * from './models/ProbeHourlyStat'
export type * from './models/ProbeDailyStat'
export type * from './models/NotificationChannel'
export type * from './models/NotificationLog'
export type * from './models/ProbeEnv'
export type * from './models/Article'
export type * from './models/ArticleRelation'
export type * from './models/Tag'
export type * from './commonInputTypes'